### ISSUE TITLE
No reports for Department?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#1]
Not a real issue, but a question.
Does the new structure allow reports also in Departments?
It could be useful to add department meetings reports. They're like a board where all team leaders from the groups come and decide something about the dept.

**Comment by sanderpotjer** [comment]
@jeckodevelopment yes, reports are available for the departments. This is a "department" view: https://volunteers.joomla.org/leadership/production-leadership-team#reports

**Comment by jeckodevelopment** [comment]
Thank you
