### ISSUE TITLE
Wrong role imported

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#10]
If you visit the Joomler profile of Tessa Mero, the role she has in PLT has been wrongly imported to her former membership in Open Source Matters (now in Honor Roll).

![tessaerror](https://cloud.githubusercontent.com/assets/733133/17849986/7e226af8-685b-11e6-8b9b-3b49af68cad7.PNG)

Tessa served as Board Member in OSM and she serves currently as Developer Advocate in PLT (and this is correct).

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for spotting, has been corrected now

**Comment by jeckodevelopment** [comment]
Thank you :)
