### ISSUE TITLE
[jvols] Duplicated users

### ISSUE THREAD

**Issue by uglyeoin** [joomla/volunteers.joomla.org#100]
Hi Sander (or anyone), 

I have a user Prasit Gebsaap who has duplicated profiles on the volunteer portal and wants one removed.  

The account with - EDIT - as the email address should be removed (or merged if that is necessary, but removal is fine). 

Thanks in advance.

**Comment by sanderpotjer** [comment]
@uglyeoin thanks, the account has been removed!
