### ISSUE TITLE
[new feature] Groups for user classes to send communications

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#101]
It would be very useful and will simplify our work if we can have lists/groups in a newsletter component based on membership classes.

Let's say if we have to send an email to all our members (team members) to inform about the new requirements (Physical address), we can have and sync a newsletter group that includes all the members in JVP.

If we have to send a communication to all our Team Leaders we could do the same (class 2 members).

Obviously for Class 1 members is easier since they're board members and less than 10 people :)

**Comment by sanderpotjer** [comment]
This has been implemented meanwhile.
