### ISSUE TITLE
Changelog page

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/volunteers.joomla.org#102]
As possible follow up for a question on Glip: 

Page listing the changes that might be interesting for teams & Joomlers about new features and changes on the Volunteers Portal. 

For example mentioning features like the positions and the possibility to mark them as "open".

**Comment by zero-24** [comment]
As this is just interesting for the TL's why not just ping the dep leads that should post it to the teams under there department if we add a new feature?

Maybe we can also add a wiki page here to this repo that explain the steps to do.
