### ISSUE TITLE
[feature request] Include team reports in the department page

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/volunteers.joomla.org#103]
Would it be possible to include reports from all team under the department reports section: https://volunteers.joomla.org/departments/marketing-communication ?

Regards,
Radek

**Comment by sanderpotjer** [comment]
@Radek-Suski thanks for the suggestion! Do you prefer the Department reports and the Department Team reports combined, or a new tab with "Department Teams Reports" besides "Reports" (or "Department Reports" so people can still find the Department specific reports easily?

**Comment by Radek-Suski** [comment]
I think combined would be perfectly fine. You can see where it has been posted in the list anyway

**Comment by jeckodevelopment** [comment]
I would like to keep anyway the reports view where to see the compete combined list of reports.

**Comment by sanderpotjer** [comment]
Team reports are now included in the departments reports tab, thanks for the suggestion @Radek-Suski
