### ISSUE TITLE
[jvols] Dublicate Team assigments

### ISSUE THREAD

**Issue by zero-24** [joomla/volunteers.joomla.org#104]
![image](https://cloud.githubusercontent.com/assets/2596554/25699807/1275324e-30c5-11e7-827d-44689eaf49d6.png)

![image](https://cloud.githubusercontent.com/assets/2596554/25699852/3f191838-30c5-11e7-86a9-bfdfc3ae1ef1.png)

### Maintainers
I joined the Maintainers and left them for a break. (so there should be one entry where I initial joined and lefted)
After my break i joined the team again (current open enty)

So i would expect (it was so in the past) that i have one entry in the active teams and one in the hnour hall.

### JSST

I have joined the team and i have been elected as `Assistant Team Leader` in the last few days.

## Result

Would be great if that could be corrected or i could do that my self?

**Comment by jeckodevelopment** [comment]
This is related to the fact we need to record the different membership class (and its duration) for each member, as requested by the bylaws.
Simplyfing, when you get elected Team Leader, you should "close" your membership as "member" and start one as TL. 
Assistant Team Leaders are normal members.

**Comment by zero-24** [comment]
> This is related to the fact we need to record the different membership class (and its duration) for each member, as requested by the bylaws

This is what is broken and I reported here?

> Simplyfing, when you get elected Team Leader, you should "close" your membership as "member" and start one as TL.

I'm no TL just ATL

> Assistant Team Leaders are normal members.

Great also TL's are members :smile: We all are just members.

**Comment by jeckodevelopment** [comment]
> Great also TL's are members 😄 We all are just members.

I agree on this, but according to the bylaws there are different types of membership

**Comment by zero-24** [comment]
But I don't see why this problem i have here is a bylaw problem? For me it just looks like a GUI issue as it worked before.

I would be happy to correct that myself but that option was removed ... :(

**Comment by mbabker** [comment]
The bylaw issue is we need to be able to track if you go from general member to (assistant) team lead or contributor.  So from that aspect it does need to have the separate entries.

And yes, there is a UI/workflow issue regarding how this is handled right now.  You really shouldn't be able to have two active memberships on one team.

**Comment by zero-24** [comment]
looks like something fixed this magicly  https://volunteers.joomla.org/joomlers/248-tobias-zulauf
