### ISSUE TITLE
[jvols] E-mail insead of Userna in password reset

### ISSUE THREAD

**Issue by wojsmol** [joomla/volunteers.joomla.org#105]
In password reset confimation step firt field have label "E-mail" insead of "Username".

**Comment by sanderpotjer** [comment]
@wojsmol Thanks! You refer to https://volunteers.joomla.org/password-reset?layout=confirm ?

This is on purpose, as e-mail is your username on this site. Or was email not working for you when resetting the password?

**Comment by wojsmol** [comment]
@sanderpotjer Yes, this is the view. When I tried to type in an email there I received an error. After entering my standard username, the password reset went well.

**Comment by sanderpotjer** [comment]
@wojsmol thanks for the info! In that case we will fix the issue when using the email.

**Comment by wojsmol** [comment]
I checked again and the glitch and the problem still occurs. The exact error message is:
```
Notice
Your password reset confirmation failed because the verification code was invalid. 
User not found.
```
