### ISSUE TITLE
[jvols] Assistant Team Leader permissions don't work for me

### ISSUE THREAD

**Issue by zero-24** [joomla/volunteers.joomla.org#106]
> Memberships are now editable by team leaders & assistants only. This change was requested for the new structure.

https://github.com/joomla/joomla-websites/issues/472

I have been electred as Assistant Team Leader for the JSST but I don't see any way to edit things in that team.

![image](https://cloud.githubusercontent.com/assets/2596554/25798787/cee43c7a-33e2-11e7-813f-719cbab9377f.png)

**Comment by sanderpotjer** [comment]
@zero-24 could you please check if you can edit things now, as your normal "member" position is now set with an end date?

**Comment by zero-24** [comment]
Works now thanks!
