### ISSUE TITLE
[jvols] There is not "Honour Roll" Entry for me as meber of the JSST

### ISSUE THREAD

**Issue by zero-24** [joomla/volunteers.joomla.org#107]
I have been elected as assistant team lead for the JSST a few days before but before i got there I was a member of that team.

This is not showed in the Honour Roll Tab, it just show my active position. The month i started in the JSST was: "Apr 2017"

![image](https://cloud.githubusercontent.com/assets/2596554/25799052/d86445aa-33e3-11e7-88c7-42da95c20423.png)

![image](https://cloud.githubusercontent.com/assets/2596554/25799093/048c0672-33e4-11e7-9e7c-34dcd9c42a7c.png)

**Comment by sanderpotjer** [comment]
@zero-24 no "end date" was set for your member position. I have now set this to april, so it is now visible on the honour roll.

**Comment by zero-24** [comment]
Thanks :+1:
