### ISSUE TITLE
[jvols] Creating a new team throws error

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/volunteers.joomla.org#108]
![image](https://cloud.githubusercontent.com/assets/4998032/25964827/7ef32784-3686-11e7-8cb5-f8ea999d21e4.png)

**Comment by aDaneInSpain** [comment]
I am logged in as a department coordinator

**Comment by mbabker** [comment]
Had the same issue too.  So it's either ACL or bad links/logic.

**Comment by aDaneInSpain** [comment]
Probably ACL, I heard the lead developer doesn't know a lot about that ;-) @sanderpotjer

**Comment by sanderpotjer** [comment]
@aDaneInSpain could you test if this is now working for you?
