### ISSUE TITLE
First Name - Last Name

### ISSUE THREAD

**Issue by brianteeman** [joomla/volunteers.joomla.org#109]
The JVP requires you to complete two fields for your name but this is not good practice (unless we have a specific need) as it does not translate well globally and it is far better to just have a single name field. 

I have spoken about this several times at Joomla (and other events) before. I only noticed it on JVP as I am updating the presentation to give at a local php usergroup

https://tee.mn/name

**Comment by jeckodevelopment** [comment]
Thanks Brian. Good point.
Anyway we need to have the complete name of each volunteer.
If we go with a single field, i'm sure we'll have people who will register using just the first name or with a nickname and that would be against our needs and rules.

**Comment by brianteeman** [comment]
That is down to the wording that we use. Please watch the presentation and you will see suggestions

Note I also span up a clone of the site and ignoring all the errors (i expect the clone or the db is not up to date) the only time we use the name is by concatenating the two fields

**Comment by brianteeman** [comment]
I should add that you say "against our rules" but no where are they defined on the site so there is nothing right now to stop someone not complying with the rules

**Comment by jeckodevelopment** [comment]
I was just going through your presentation and you're completely right.
The two fields are sons of a standardization, obviously.
I can support your idea but we need also to be very clear on what we do expect from them, otherwise it becomes a mess and we can't use anymore the JVP as the Volunteers registry required by the bylaws.

**Comment by brianteeman** [comment]
> The two fields are sons of a standardization, obviously.

They are a western standard and this is a global site

**Comment by jeckodevelopment** [comment]
that's what i meant

**Comment by sanderpotjer** [comment]
Thanks for bringing up this point @brianteeman.

I am happy to combine the first and last name fields into a single "Full name" field. I can't imagine the OSM bylaws mention to have separate fields for the name input. We could add a descriptive line explaining that they need to enter their full name, and not a nickname. Any suggestions/requirements for that @jeckodevelopment ?

**Comment by jeckodevelopment** [comment]
We need to request the full name.
It's not a problem to have just one textbox for that, but we need to have a clear "note/message" to inform that we need the full name.

**Comment by brianteeman** [comment]
You also need to state if you require it in Latin characters. If it is ok to give it in greek for example then you dont need to

**Comment by jeckodevelopment** [comment]
Well, we need the legal name. I'd suggest to have it in Latin characters, but it shouldn't be a requirement. But i need to check better.

**Comment by brianteeman** [comment]
The legal name would not be in latin characters them :)

**Comment by brianteeman** [comment]
Then not them

**Comment by sanderpotjer** [comment]
This is now implemented, so only Full name. Thanks @brianteeman
