### ISSUE TITLE
Integrate signature of CoC

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#110]
We should enforce our volunteers to sign the Code of Conduct when they register to the Volunteers Portal and we should track evidence of this signature.

Is it possible to add this feature to the JVP?

it would be useful also to track the signature of others agreements (JCA / JEDCA) in the same place, maybe as a checkbox that can be actioned by the Secretary or recorded automatically if we remove the need of Echosign.
In this way our JVP would become the unique registry for memberships and agreements signed.

**Comment by sanderpotjer** [comment]
@jeckodevelopment it is not exactly clear to me what you are looking for. A checkbox that can be set by the secretary that an specific agreement is signed? Or the possibility to set a digital signature?

**Comment by jeckodevelopment** [comment]
It would be awesome to integrate something like a digital signature for these agreements.
Do you think that could it be possible?

**Comment by sanderpotjer** [comment]
@jeckodevelopment looking into the options, but not really easy. Depends also a bit on the requirements. Does PDF documents needs to be signed? Or a place on a webpage that needs a signature?

**Comment by jeckodevelopment** [comment]
So currently we have echosign for that, but i guess we can switch to something easier to manage.

**Comment by yvesh** [comment]
There is an API for Echosign, not sure how good it is, but it doesn't look too complicated - there are also some PHP libraries around it.

https://secure.na1.echosign.com/public/docs/restapi/v2

But do we really want people to sign the CoC or is a checkbox for this enough? Not sure on the legal impact.. The sign on Echosign has ofc a better effect and feels more valuable.

**Comment by sanderpotjer** [comment]
As a first step the checkbox is now available for the secretary in the backend when editing a Joomler:

<img width="408" alt="screen shot 2017-07-03 at 23 10 07" src="https://user-images.githubusercontent.com/522834/27807976-d7ff00b8-6044-11e7-97c7-89660036da79.png">

It is also possible to filter the list on the CoC:
<img width="499" alt="screen shot 2017-07-03 at 23 10 20" src="https://user-images.githubusercontent.com/522834/27807980-e272c2aa-6044-11e7-93ec-fd9eb34eecd4.png">

@jeckodevelopment could you have a look if this is OK for now?

**Comment by jeckodevelopment** [comment]
Well, this could work for NdA and other specific agreements.
I'd say that Code of Conduct could be signed with a checkbox marked by the volunteers directly (like an agreement box).
Otherwise I need to receive a notification at each CoC signature and reflect the changes in the JVP for each volunteer.

**Comment by sanderpotjer** [comment]
@jeckodevelopment ah, that wasn't clear to me. So, what is the correct CoC that needs to be used/linked to? And does everybody on the Volunteers portal needs to "sign" the checkbox for the CoC or only the people active as member in a team?

**Comment by yvesh** [comment]
@sanderpotjer should be everyone probably (required checkbox for registration).. what's up to discussion is if we want a checkbox or a real signature, that's also depends a bit of the outcome of the working group with @aleksanderkuczek

**Comment by sanderpotjer** [comment]
@yvesh so its better to wait on the outcome of the working group?

**Comment by aleksanderkuczek** [comment]
Give us 4 weeks and you will get one single contract that includes Code of
Conduct which we can integrate with Volunteer Porta

**Comment by jeckodevelopment** [comment]
thanks guys

**Comment by sanderpotjer** [comment]
@aleksanderkuczek any updates on the single contract?

**Comment by aleksanderkuczek** [comment]
Hey,

yes. We have preliminarily agreed that we need to checkboxes. One for Code
of Conduct and the other one for contributor agreement. The final text
should be approved in Rome. Is that feasible?

Feel free to ask any additional questions you have.

Thanks,
Aleksander

2017-10-16 11:21 GMT-06:00 Sander Potjer <notifications@github.com>:

**Comment by aleksanderkuczek** [comment]
@sanderpotjer I'm ready to move on with this. Will you be in Rome to discuss the details or shall we do it online?

**Comment by sanderpotjer** [comment]
@aleksanderkuczek I will be there, so happy to discuss in person.

**Comment by aleksanderkuczek** [comment]
@sanderpotjer great. Do we have any mockups with a suggested solution or should I provide some?

**Comment by sanderpotjer** [comment]
@aleksanderkuczek there are no mockups, as the requirements are not clear yet :) So anything is welcome.

**Comment by aleksanderkuczek** [comment]
@sanderpotjer Here are the two mockups of modified screens.

New users: https://preview.uxpin.com/2bdf8c9869b98dcb599fbb65157c27fc7c7d2cef#/pages/77337501/simulate/no-panels?mode=i
Existing users: https://preview.uxpin.com/2bdf8c9869b98dcb599fbb65157c27fc7c7d2cef#/pages/77631826/simulate/no-panels?mode=i

Feel free to give me your feedback. 

[edit: Updated mockups after talks with Sander at JWC17]

**Comment by sanderpotjer** [comment]
@aleksanderkuczek are both the JCA and CoC checboxes required fields? In the mockup only the CoC has `(required)` behind the label? And is there a difference in the required fields for contributors/members?

And once agreed, should the fields be visible in the profile as read only, or completly hidden? Assuming you don't want people to remove the tick in the checkbox?

**Comment by aleksanderkuczek** [comment]
@sanderpotjer That was my mistake. It was a matter of an overlay on the mockups. I have fixed it now. Both should be required for members. Only CoC for contributors.

Once agreed we could keep the fields as read-only as we do not want to track the changes when someone has check and un-check it.

**Comment by sanderpotjer** [comment]
@aleksanderkuczek thanks for the info!

**Comment by sanderpotjer** [comment]
@aleksanderkuczek this now all ready for release:

## Registration
Code of Conduct required
<img width="897" alt="screen shot 2018-01-04 at 20 48 50" src="https://user-images.githubusercontent.com/522834/34581519-f8b16ec6-f190-11e7-9ea8-3a2d5172339a.png">

## For existing contributors after login
Code of Conduct required
<img width="891" alt="screen shot 2018-01-04 at 20 49 08" src="https://user-images.githubusercontent.com/522834/34581538-15c60ac6-f191-11e7-8f6f-41922c69dd2f.png">
<img width="897" alt="screen shot 2018-01-04 at 20 49 14" src="https://user-images.githubusercontent.com/522834/34581542-1bdf348c-f191-11e7-8461-d0b41fb7bcd0.png">

## For existing members after login
Code of Conduct & Joomla Contributors agreement required
<img width="898" alt="screen shot 2018-01-04 at 20 49 30" src="https://user-images.githubusercontent.com/522834/34581547-237b6756-f191-11e7-8437-49987f69f366.png">
<img width="887" alt="screen shot 2018-01-04 at 20 49 36" src="https://user-images.githubusercontent.com/522834/34581554-2a35f8a4-f191-11e7-8c9f-6232a76011d3.png">

Should this be released when possible or after/on a specific date? It might need some communication with the community to make clear why this was changed etc...

**Comment by yvesh** [comment]
@sanderpotjer the text needs to be finalized (and approved) by the board. After that it can go live.

**Comment by aleksanderkuczek** [comment]
@sanderpotjer @yvesh I will get the approval of the agreement from the board this week. What about Code of Conduct? Do you have it?

**Comment by sanderpotjer** [comment]
@aleksanderkuczek right now the link behind the text is https://www.joomla.org/about-joomla/the-project/code-of-conduct.html. If the Code of Conduct is updated I would suggest updating the text over there.

**Comment by jeckodevelopment** [comment]
@sanderpotjer Contributor agreeement is pending approval currently

**Comment by brianteeman** [comment]
I guess this can be closed as the contributor agreement was rejected by the board

**Comment by zero-24** [comment]
> I guess this can be closed as the contributor agreement was rejected by the board

Where or better why? The [latest report from OSM is from 29.03.](https://volunteers.joomla.org/board-of-directors/reports/772-osm-inc-full-board-meeting-march-29-2018) and that don't include anything about COC or I'm missing something?

**Comment by brianteeman** [comment]
Because it happened much earlier https://volunteers.joomla.org/board-of-directors/reports/752-osm-inc-full-board-meeting-february-15-2018

> #2018/020 - Remove the existing Code Contributors’ Agreement effective immediately.
Proposed by Robert Jacobi, seconded by Michael Babker.
The motion passed with unanimous consent.

I guess @jeckodevelopment forgot to update the team here

**Comment by zero-24** [comment]
Ah ok :)

**Comment by ot2sen** [comment]
For the Code of Conduct part it could be made simple that people need to agree on submit/register similar to how you download a GPL extension from Sobi for example (click download)
https://www.sigsiu.net/center/sobipro-component

**Comment by zero-24** [comment]
@ot2sen that is the technical part but given the point Brian made the complete COC got rejected by the board so nothing to show in that box ;).

**Comment by brianteeman** [comment]
sorry i completely messed up. i misread this as being about the CLA and the CoC

i guess it can stay open for the coc part

**Comment by ot2sen** [comment]
From the screenshots in the thread it was about both so the note about Joomla Contributor Agreement being rejected was valid for this issue.
Would be logic to use same approach for the Code of Conduct acceptance as in your Privacy Policy PR Brian, so that people cannot complete registration without accepting the CoC.

**Comment by brianteeman** [comment]
@ot2sen perhaps although the CoC doesnt appear to exist yet either. And personaly speaking I would be against that type of enforcement - but that is beyond the scope of this issue tracker
