### ISSUE TITLE
[jvols] New team needed

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/volunteers.joomla.org#113]
I need a team created called "Contributer Agreement Working Group". It should have Aleksander Kuczek as team leader.

And should be in my department "Legal and Finance"

**Comment by sanderpotjer** [comment]
@aDaneInSpain you should be able to add that team yourself as department coordinator:
<img width="937" alt="screen shot 2017-05-24 at 09 46 36" src="https://cloud.githubusercontent.com/assets/522834/26392163/f0d546a0-4065-11e7-9c4c-bd0dce6ecad9.png">

See button "Add Team" in the Department Teams tab.

**Comment by aDaneInSpain** [comment]
So I can. Sorry!

**Comment by sanderpotjer** [comment]
No problem :)

**Comment by aDaneInSpain** [comment]
Actually no, I can't because I run into this: https://github.com/joomla/volunteers.joomla.org/issues/108

**Comment by aDaneInSpain** [comment]
Yes, now it works. Thanks.
