### ISSUE TITLE
Adding new team member to a sub team does not work

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/volunteers.joomla.org#114]
I am unable to select a position for the user

![image](https://cloud.githubusercontent.com/assets/4998032/26395147/82d86fd8-406f-11e7-8e42-5730ad3abb96.png)

**Comment by sanderpotjer** [comment]
@aDaneInSpain could you logout and login on the portal? I can't duplicate this issue at the moment, and think something is wrong with the session data. As the "Department" field should not be visible, only the Team (disabled) field.

**Comment by aDaneInSpain** [comment]
Logging out and back in helped. Not sure why. I just logged in today, it was not an old stored session.
