### ISSUE TITLE
Checkbox for permission to send things

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/volunteers.joomla.org#115]
>Hi Sander as per the current board meeting we need to add a check box next to the address giving permission for the project to use it to send people things - rewards, stickers, tshirts etc.  An opt in basically.

**Comment by sanderpotjer** [comment]
Available now in the profile:
<img width="920" alt="screen shot 2017-07-03 at 23 05 32" src="https://user-images.githubusercontent.com/522834/27808001-15f63058-6045-11e7-9416-f686f9e2a845.png">

**Comment by jeckodevelopment** [comment]
Thank you Sander
