### ISSUE TITLE
[jvols] Top-Navigation isn't shown

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#116]
Top-Menu is missed (Firefox 54 – 64-bit):
![bildschirmfoto 2017-06-16 um 18 10 51](https://user-images.githubusercontent.com/8235763/27234984-53d186fe-52bf-11e7-97be-c2701ad7ff5b.jpg)

**Comment by jeckodevelopment** [comment]
confirmed.
![immagine](https://user-images.githubusercontent.com/733133/27235463-3c007254-52c1-11e7-9269-f01cc6ee9eda.png)

**Comment by ghost** [comment]
works, thanks.
