### ISSUE TITLE
[jvols] Double account GSoC Volunteer

### ISSUE THREAD

**Issue by hvdmeer** [joomla/volunteers.joomla.org#118]
I stumbled across this double account, perhaps one could be deleted?

https://volunteers.joomla.org/joomlers/2043-flavius-andrei-isac
https://volunteers.joomla.org/joomlers/2047-flavius-andrei-isac

**Comment by sanderpotjer** [comment]
@hvdmeer thanks! Reached out to Flavius to check which one is the preferred account.

**Comment by hvdmeer** [comment]
@sanderpotjer Found another one today and thought why not check all.
https://volunteers.joomla.org/joomlers/251-gabriel-flores
https://volunteers.joomla.org/joomlers/1863-gabriel-flores

https://volunteers.joomla.org/joomlers/652-franz-wohlkoenig
https://volunteers.joomla.org/joomlers/1911-franz-wohlkoenig

https://volunteers.joomla.org/joomlers/672-giuseppe-scinica
https://volunteers.joomla.org/joomlers/1829-giuseppe-scinica

https://volunteers.joomla.org/joomlers/563-rob-bezouwen
https://volunteers.joomla.org/joomlers/1766-rob-bezouwen

Two Martin Mueller's?
https://volunteers.joomla.org/joomlers/1638-martin-mueller-2
https://volunteers.joomla.org/joomlers/1642-martin-mueller-3

Spam?
https://volunteers.joomla.org/joomlers/1147-rachel

**Comment by sanderpotjer** [comment]
@hvdmeer thanks!
