### ISSUE TITLE
How upgrade the official documentation ?

### ISSUE THREAD

**Issue by ZerooCool** [joomla/volunteers.joomla.org#120]
How upgrade the official documentation ?

Can you look this : https://www.visionduweb.eu/wiki/index.php?title=Prise_en_main_de_Joomla#Page_404_par_d.C3.A9faut_de_Joomla

I see, error 404 soft seo in the doc.
I see, error 404 hard seo with a forum. 

I have not seen any references for hard seo and 404 error in official documentation. It may be important, what do you think?

**Comment by sanderpotjer** [comment]
@ZerooCool this repository is only for issues with https://volunteers.joomla.org. The  https://www.visionduweb.eu/ website is not an official Joomla site, so I suggest to contact the owners of that website.

**Comment by ZerooCool** [comment]
Hello, I hurt to express myself.
I discovered in my research that the management of page 404 error proposed by Joomla! Proposes to treat page 404 with soft-seo

I read on a forum that it would REALLY BETTER to use hard seo.

That's why I share this information, and I would like to know if it is relevant to add it to the official documentation, and how ...

**Comment by sanderpotjer** [comment]
@ZerooCool the official documentation can be found on https://docs.joomla.org. That is a wiki, so after creating an account you can add/edit the pages that should be updated. See https://docs.joomla.org/JDOC:How_to_Contribute_to_Joomla!_Documentation

**Comment by ZerooCool** [comment]
Ok i create my account to the Joomla Wiki docs.
[Resolved]
