### ISSUE TITLE
Indicator for Team Status

### ISSUE THREAD

**Issue by mbabker** [joomla/volunteers.joomla.org#121]
The team records already have a "Status" field which should presumably be used to set its status within the project.  Would it be possible to display this somehow outside of the edit page?

**Comment by sanderpotjer** [comment]
Added as label next to the team titles on the overview and detail views, e.g.: https://volunteers.joomla.org/teams & https://volunteers.joomla.org/teams/automated-tests-working-group

@mbabker thanks for the suggestion!
