### ISSUE TITLE
[jvols] Joomla-Docs-User give Error

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#122]
I append my Docs-User to my [Joomla-Profile](https://volunteers.joomla.org/joomlers/1911-franz-wohlkoenig). Click on Docs-Username give `Bad Titel: The requested page title is empty or contains only the name of a namespace. `

**Comment by sanderpotjer** [comment]
@franz-wohlkoenig thanks for reporting the issue. Fixed now!
