### ISSUE TITLE
add crowdin icon

### ISSUE THREAD

**Issue by zero-24** [joomla/volunteers.joomla.org#123]
All integrations have a icon but it looks like the crowdin one is missing:

![image](https://user-images.githubusercontent.com/2596554/27878325-21443b9c-61be-11e7-89e8-a5246464b7e3.png)

Maybe we can ask crowdin about a smal icon like they had on twitter:
https://pbs.twimg.com/profile_images/821985679769030656/tGUepzTM_400x400.jpg
for the media kit page: https://crowdin.com/page/media-kit

**Comment by mbabker** [comment]
Crowdin doesn't have a font icon in Font Awesome or IcoMoon.  So the best you could do would be to use an image file right now.  Unless someone wants to do the work to add their logo to our IcoMoon font set.

**Comment by Sandra97** [comment]
It's on its way ;) 
Crowdin will see that with IcoMoon and will keep me informed.

**Comment by zero-24** [comment]
is this: 
![image](https://user-images.githubusercontent.com/2596554/28500119-bc2d7e08-6fc3-11e7-9b19-2d7d1bc9fd63.png)

The icon Crowdin provided or just a placeholder ;)

**Comment by Sandra97** [comment]
It's not the "Crowdin' IcoMoon icon, but the one added by Sander does perfectly the job and solves the mobile issue
.

**Comment by roland-d** [comment]
@Sandra97 Is there any progress here?

**Comment by Sandra97** [comment]
I don't have any news. I'll send a new message to my contact.
