### ISSUE TITLE
[jvols] Link from Volunteer- to Forum-Profile don't work 

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#124]
I appended my Forum-Profile to my Volunteer-Profile. 
Click on Link shows at Forum-Page this Message:
![bildschirmfoto 2017-07-06 um 06 59 10](https://user-images.githubusercontent.com/8235763/27896193-a3293d24-6218-11e7-91fe-f8685be08f58.jpg)

**Comment by hvdmeer** [comment]
It works for me. You added just the account number?

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Sorry, i missed the "ID". Now it works. Thanks for helping.

**Comment by ghost** [comment]
Where to find my ID? I saw a number at url but its routing to another Member as this Number is the Menu-ID.

**Comment by zero-24** [comment]
Just log in to your profile and see the id you find on the profile page ;)

**Comment by ghost** [comment]
Thats what i thought ;-) got:
![bildschirmfoto 2017-07-06 um 08 11 55](https://user-images.githubusercontent.com/8235763/27897824-dcc21d08-6222-11e7-900c-a5d88887126c.jpg)

**Comment by hvdmeer** [comment]
I searched myself on the forum to get the id.
Yours is 707223.

**Comment by ghost** [comment]
Thanks @hvdmeer @zero-24  – now it works.
