### ISSUE TITLE
forced to user profile, cant navigate anywhere else

### ISSUE THREAD

**Issue by mandville** [joomla/volunteers.joomla.org#125]
it seems impossible for me to go update a team meeting report without every time landing on the "edit my profile" page. can this be rectified so i don't have to go to the profile page , and instead go to the team reports page , which is not where i want to go to

**Comment by sanderpotjer** [comment]
@mandville this message is displayed on top of your profile page:
<img width="920" alt="screen shot 2017-07-12 at 21 45 35" src="https://user-images.githubusercontent.com/522834/28136878-85763ede-674b-11e7-97a1-365c38c4584b.png">

So you are redirected to your profile as an active member of a team, to fill in your mailing address. If you filled that in, you will no longer be redirected.

**Comment by mandville** [comment]
I have provided my details. therefore the redirection should not happen. there are also new tabs and checkboxes on that page since last time i updated my profile. 
your assumption i have not provided my details - where did that come from

**Comment by sanderpotjer** [comment]
@mandville What username are you using to login?

**Comment by sanderpotjer** [comment]
As mentioned in Glip it seems that @mandville provided the address directly to the secretary. I am not aware of such cases and a seperate database for addresses, so the Volunteers Portal doesn't have a feature for that at the moment to prevent redirecting for members without an address provided. Is that something that needs to be added @jeckodevelopment?

**Comment by jeckodevelopment** [comment]
is this still open?

**Comment by sanderpotjer** [comment]
I assume Claire is the only one at the moment that provided the details directly, so not adding any code to handle this exception. Instead, I added some dummy data in the required field, so @mandville you should be able to browse to Volunteers Portal normally again.
