### ISSUE TITLE
Show if team members filled in their address to team leaders

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/volunteers.joomla.org#126]
Show an indicator visible for team leaders next to the members of a team if the provided their address (required by OSM by-laws), **not** the actual address.

**Comment by sanderpotjer** [comment]
Visible for team leaders / department coordinators now under column "Address":
<img width="678" alt="screen shot 2017-07-19 at 21 54 50" src="https://user-images.githubusercontent.com/522834/28386813-14d11190-6ccd-11e7-8062-fd9c86660fdc.png">

**Comment by jeckodevelopment** [comment]
This is a great improvement. Thank you Sander.
