### ISSUE TITLE
Icon forum and docs on mobile

### ISSUE THREAD

**Issue by hvdmeer** [joomla/volunteers.joomla.org#127]
When I visit my profile on my mobile the icons for the forum and docs are exactly the same, so you have no idea where they link to. Also the grey area on the right is not correct.
![vol-icon](https://user-images.githubusercontent.com/7062995/28428314-4d89117a-6d79-11e7-882a-84bcf1c9338c.png)

**Comment by mbabker** [comment]
> Also the grey area on the right is not correct.

That one is because we don't have an icon for Crowdin at the moment.  Apparently it's a work in progress though to create one for use with our IcoMoon font set.

**Comment by sanderpotjer** [comment]
@hvdmeer thanks for reporting! Labels are now visible for the Joomla icons. For Crowdin I added a temporary "language" icon, while waiting on icon in #123
