### ISSUE TITLE
Can't edit team members position in frontend

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#129]
I'm not able to change anymore the Position of a team member/leader/atl in the frontend.

![immagine](https://user-images.githubusercontent.com/733133/28498099-b524a0e6-6f96-11e7-833f-01b26e19afeb.png)

**Comment by zero-24** [comment]
Isnt that the job of the team leader? ;)

**Comment by jeckodevelopment** [comment]
Yes, but, as secretary, once i had this opportunity. Now i can only from the backend.

**Comment by zero-24** [comment]
Is't that egnoth? As for that feature we need another fallback + extra code just to handle that single person feature...

**Comment by jeckodevelopment** [comment]
No problem than.
I noticed the change but i didn't know that it was intentional due to new code development :)
Thank you @zero-24

**Comment by sanderpotjer** [comment]
@jackodevelopment this is indeed requested and changed on purpose, to make sure that the history is correct. So you can't change a position, you need to end the current one and create a new one. However, working on an improved workflow for this

**Comment by jeckodevelopment** [comment]
Thank you Sander
