### ISSUE TITLE
[Frontend] Cancel button doesn't work in the member edit screen

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#130]
As per the title, if i try to edit membership details of a member, in several cases if I click on the Cancel button, no action is taken.

Can you please check?

**Comment by Sandra97** [comment]
I had the same issue with the Save button when adding a new member/contributor. But I thought it was just me as after a while it worked

**Comment by jeckodevelopment** [comment]
I have this issue also with the Save button. But if i click several times on buttons, at the end they work.
JS?

**Comment by zero-24** [comment]
Js cache? Any error in the js console?

**Comment by sanderpotjer** [comment]
Can't duplicate this, possibly related to template JS caching issues that should be resolved. Please re-open if this shows up again.
