### ISSUE TITLE
Unexisting volunteer in GSOC

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#132]
In https://volunteers.joomla.org/teams/google-summer-of-code-joomla-team

there's a blank volunteer listed as member.

![image](https://user-images.githubusercontent.com/733133/28565418-7ad3498c-712c-11e7-9b29-f43ea3dd2992.png)

https://volunteers.joomla.org/joomlers/2043- that gives a 404

**Comment by yvesh** [comment]
Hm, not sure who that is. Looks like all our students are still there. Any information on him in the backend Luca? If not just remove it, weird!

**Comment by hvdmeer** [comment]
In #118 I mentioned this user being a double with user 2047. Sander removed all duplicates, someone with enough rights to do so could switch 2043 for 2047.

**Comment by sanderpotjer** [comment]
@jeckodevelopment 2043 as member has been removed. Is already listed as 2047.

**Comment by jeckodevelopment** [comment]
Thank you
