### ISSUE TITLE
Doublicate entry for the Anibal Sanchez in the GSoC 17 Expand Extension Manager

### ISSUE THREAD

**Issue by zero-24** [joomla/volunteers.joomla.org#133]
see: 

![image](https://user-images.githubusercontent.com/2596554/28565898-d904f428-712d-11e7-9eae-f5963a451829.png)

Looks like ther is a dublicate assigment for him here:
![image](https://user-images.githubusercontent.com/2596554/28565926-ed551f34-712d-11e7-90b0-cb66a9f2e871.png)

**Comment by Sandra97** [comment]
Lucky Anibal, he succeeded to clone himself. ;)

**Comment by hvdmeer** [comment]
I believe I've seen this with another user. But isn't it correct? Being a member and leader?

**Comment by jeckodevelopment** [comment]
@hvdmeer once one becomes Team Leader he/she ends his membership as "member" and starts a new one as Team Leader.

**Comment by sanderpotjer** [comment]
The end-date was indeed not set for the "member" position, changed that now so it is displayed correctly.
