### ISSUE TITLE
[Map] Showing undefined beyond username

### ISSUE THREAD

**Issue by yvesh** [joomla/volunteers.joomla.org#134]
The map on the main page of the VP is showing undefined below any name in the google maps info window.

![2017-07-26-00 02 27](https://user-images.githubusercontent.com/897638/28595889-44d9ef10-7196-11e7-927c-2325a246e7c0.png)

locations[i].address is the issue

P.S.: I am not sure if it's a good idea to load the whole database on users (>1000) into a json string, including image url and location directly as json there.. Bit too easy to scrap imo :-)

**Comment by sanderpotjer** [comment]
@yvesh thanks for reporting!

Was displaying city & country in the past (so not the full address!), but removed as info is already clear from location on the map ;-)
