### ISSUE TITLE
[jvols] Typo in Profile

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#135]
Last Members Role called "Liasion", should be "Liaison" say my Translation-Tool.

![bildschirmfoto 2017-07-27 um 16 48 59](https://user-images.githubusercontent.com/8235763/28676706-a411067a-72eb-11e7-8b6d-4a342dd316d5.jpg)

**Comment by zero-24** [comment]
Thanks fixed. Please close the issue.
