### ISSUE TITLE
H2 with different sizes

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#14]
If you go to the jvols home page: `https://volunteers.joomla.org/` in the new module (great addition) that shows latest reports, module title is smaller than report titles.
Both titles are H2, but the one of Reports is bigger.
I guess we need to have smaller titles for reports otherwise we should use H1 for the module title.

![jvols-h2](https://cloud.githubusercontent.com/assets/733133/17894994/da905a5c-694b-11e6-993d-e9188705d30e.PNG)

**Comment by mbabker** [comment]
Report titles there should be H3, not H2.  The module title shouldn't be promoted to H1.

**Comment by jeckodevelopment** [comment]
yes, you're right.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks, has been corrected

**Comment by jeckodevelopment** [comment]
Thank you
