### ISSUE TITLE
Profile Settings - Peakon

### ISSUE THREAD

**Issue by brianteeman** [joomla/volunteers.joomla.org#140]
`Please indicate below if you agree to your details being shared with Peakon. Peakon is a third party with whom the Joomla! Project is working as part of the Volunteer Engagement Program. Your Name, Email Address and Country will be shared with their system for the sole purpose of sending you surveys. data provided to Peakon through the surveys the Joomla! Project will send you is completely anonymous however. More Information
`

Note that the sentence beginning "data provided" should begin with a capital letter

**Comment by sanderpotjer** [comment]
@brianteeman thanks!
