### ISSUE TITLE
[New feature] Add link to the Certified Users Directory

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#141]
A way to "officially recognize" our Certified Users and to bring awareness to our Certification Program is to add to the Volunteer profile a link to their personal page on the Certified Users Directory.
We do almost the same with other Joomla properties, like Forum and Docs.
![image](https://user-images.githubusercontent.com/733133/29252131-d0c3ae60-8061-11e7-960c-5e6a5d3039d2.png)

We could have a button like the one for Docs that will link to his/her profile on CUD.

Each certified user can link his volunteer profile to the CUD:
`https://exam.joomla.org/directory/user/____`
where ____ will be filled out by the user with ID-alias

This field could be optional and the icon won't appear if the user won't fill out the fill with the link to his/her profile.

This is a way to bring value to our Certification Program and a way to recognize volunteers their success. 

@sam-suresh , @yvesh , @joomv  for your review/advice.

Thanks!

**Comment by sam-suresh** [comment]
Certification is not contribution related like Forum and Docs which are contribution related profiles. 

However its still good to incorporate the certification profile to volunteer profile.

**Comment by jeckodevelopment** [comment]
Closing as we have an awesome PR to address it!
Thanks!
