### ISSUE TITLE
Volunteer Portal Login trouble.

### ISSUE THREAD

**Issue by rgmears** [joomla/volunteers.joomla.org#142]
I was on my profile page in the Volunteer Portal. I made a couple of modifications (including opting out of the Peakon survey) and saved them. 
I subsequently get the following error message when I try to log in. 
Username and password do not match or you do not have an account yet.

**Comment by zero-24** [comment]
can you try the email and not the username?

**Comment by sanderpotjer** [comment]
@rgmears are you trying to login with your username or emailadres? The username is replaced by emailadres, so if you use the emailadres I think it will work.

**Comment by sanderpotjer** [comment]
Just changed the `Username and password do not match or you do not have an account yet.` into `Email and password do not match or you do not have an account yet.` to prevent possible confusion. Thanks.

**Comment by rgmears** [comment]
I had previously logged in with my Username, which is what was saved in my browser. I just tried my email address (which was not saved) and was able to log in. Should I switch to using my email address?

**Comment by jeckodevelopment** [comment]
yes, you should @rgmears

**Comment by rgmears** [comment]
OK
