### ISSUE TITLE
Volunteer Portal address field

### ISSUE THREAD

**Issue by rgmears** [joomla/volunteers.joomla.org#143]
I live outside of a city. My closest neighbour is 600 metres away. I have what is called a civic (or 911) address. But if you mailed anything to me at that address it would not be delivered. That's because my mailing address is a P.O. Box. The address field on the Profile page does not allow for this.

**Comment by sanderpotjer** [comment]
@rgmears what change is needed to allow the P.O. Box?

**Comment by rgmears** [comment]
Add, I suppose, a Mailing Address field.

For example, my civic address is 7049 PR205E
My city is actually a locale named Silver Plains

My mailing address though is:
Box 7, Group 310, RR 3
Morris (closest town where post office is), Manitoba

Province is the same for both.

**Comment by sanderpotjer** [comment]
@rgmears thanks for your input!

@jeckodevelopment what does the OSM bylaws requires? The living or mailing address? (or both?)

**Comment by jeckodevelopment** [comment]
@sanderpotjer sorry for delay!
P.O. Boxes are considered valid addresses in some countries, so we allow to use them (e.g. in UK).

According to our bylaws, we need "mailing address" (ref. Section 4.03)

**Comment by rgmears** [comment]
There needs to be two fields for P.O. Box mailing addresses:
    P.O. Box
    City

State/Province and Zip/Postal codes are the same for both (in Canada).

**Comment by sanderpotjer** [comment]
Mailing address section now contains the fields to set a complete mailing address beside the city/county location on the map.
