### ISSUE TITLE
Allow URLs in the "Get involved" tab

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#147]
Hello,

Automatic link parsing would be useful in the "Get involved" tab

![immagine](https://user-images.githubusercontent.com/733133/29725411-4d044a8e-89cc-11e7-8ec6-cce27d1f07ad.png)

**Comment by sanderpotjer** [comment]
@jeckodevelopment you don't have the editor visible for the "How to get involved" field when editing a team? 
![getinvolved](https://user-images.githubusercontent.com/522834/29725805-b1dfdf8a-89cd-11e7-8b5d-7c63c9c41797.gif)

**Comment by jeckodevelopment** [comment]
Yes i do :)
Sorry for that!
I also used a class for the link.
