### ISSUE TITLE
No reports displayed at a Department Level

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#149]
If you go to 
Programs > Reports and then click on the link "Browse all reports from this team" ![immagine](https://user-images.githubusercontent.com/733133/29831638-0af5d384-8ce6-11e7-9354-968613326ba8.png)
 you'll get an empty page:

![immagine](https://user-images.githubusercontent.com/733133/29831529-b6ab3526-8ce5-11e7-961e-fa17e25470b0.png)

Resulting URL is: https://volunteers.joomla.org/reports?filter_category=d.56

And it's correct because Programs as Dept doesn't have any report.
But, if you go to: Departments > Programs > Reports 
you'll see all the reports under such department
https://volunteers.joomla.org/departments/programs#reports 

![immagine](https://user-images.githubusercontent.com/733133/29831600-eba7d202-8ce5-11e7-8833-590513186f51.png)

**Comment by jeckodevelopment** [comment]
Let me clarify:
If I go to 
Departments > [DEPARTMENT] > Reports i'll see all the reports for teams under such department
If I click on 
![immagine](https://user-images.githubusercontent.com/733133/29831638-0af5d384-8ce6-11e7-9354-968613326ba8.png)
in such page, i can see just the reports at the Department level.

**Comment by zero-24** [comment]
hmm the URL should be `https://volunteers.joomla.org/reports?filter_category=56` without the `d.` maybe a typo in the code?

**Comment by zero-24** [comment]
https://github.com/joomla/volunteers.joomla.org/pull/150

**Comment by zero-24** [comment]
Yes it was a typo

**Comment by jeckodevelopment** [comment]
Thanks Tobias!

**Comment by sanderpotjer** [comment]
@jeckodevelopment it was requested in #103 to include team reports in the department reports tab. Before that, it was only showing the reports of the specific department. 

That's where the link "Browse all reports from this team" comes from (which should be departments indeed). Right now the "Reports" page doesn't have an option to list all reports from both the department and the department team. 

So I think there are two options to solve this:
1) Change the button wording to make clear you can browse the department reports only by clicking on the link
2) Change the reports page, so the department team reports are also included when filtering for the department. 

@zero-24 thanks for the PR, but that is not fixing the issue. The d in front is on purpose (d = department, t=team). Easiest at time of implementing the department structure within the current setup.`?filter_category=56` is showing all reports, not filter active.

**Comment by jeckodevelopment** [comment]
Thanks @sanderpotjer 
I guess that the 1 is the easiest solution, change the wording in the button, specifying that it will open just the reports of the Department.
Something like: "Browse all reports from the Department Coordination Team" that should be the name of the Department lead.
Otherwise, we should add more "levels" in the filter, allowing the user to specify whether he/she would like to see the Department Coordination Team reports or reports from teams under a certain department.

Thank you ;)

**Comment by sanderpotjer** [comment]
Changed the button text for now.
