### ISSUE TITLE
Bad time for liaision calculation

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#15]
It appears (always worked in this way) that liaison are calculated every month... just look at many Working Groups and you can see that the starting month for liaison is the current month. 

But, if you go to Distribution Working Group's Honor Roll: `https://volunteers.joomla.org/teams/distribution-working-group#honorroll` you can see that a member left a team (Nov 2014) before to join it (Aug 2016). And this is not correct.

![badliaison](https://cloud.githubusercontent.com/assets/733133/17895999/4be71792-694f-11e6-8b48-916a2dc3f1fc.PNG)

**Comment by sanderpotjer** [comment]
@jeckodevelopment the liaisons are not calculated either, so my guess is a general bug around liaisons

**Comment by jeckodevelopment** [comment]
Ok! please have a look... in fact most of liaisons start on Aug 2016

**Comment by sanderpotjer** [comment]
@jeckodevelopment found the issue, for those items the "date started" was not set. Fixed this now by setting the created date as date started for those without a date set. For new items the "today" date is already set as default when adding a new member to a team.

**Comment by jeckodevelopment** [comment]
Great, thank you @sanderpotjer :)
