### ISSUE TITLE
Unable to select [secretary knows] for location - country

### ISSUE THREAD

**Issue by mandville** [joomla/volunteers.joomla.org#151]
Unable to select [secretary knows] for location - country. This option is available for all other options,

**Comment by sanderpotjer** [comment]
@mandville that is correct and on purpose. There is no possibility to select that as user. That value can onlys be set manually upon request of the secretary.

**Comment by jeckodevelopment** [comment]
I'd suggest to put a general address. At the moment just one user requested this special condition.

**Comment by mandville** [comment]
i was probably that user. please enable the option to select secretary knows for all address options
