### ISSUE TITLE
user links do not work as expected 

### ISSUE THREAD

**Issue by mandville** [joomla/volunteers.joomla.org#152]
example
https://volunteers.joomla.org/joomlers/2240-thomas-gronbek-andersen
forum link https://forum.joomla.org/memberlist.php?mode=viewprofile&u=thomasga expected a numeric value instead &u=tomasga
certification image links to https://exam.joomla.org/directory/user/thomasga leads to no user 
expected format https://exam.joomla.org/directory/user/000-name
docs - https://docs.joomla.org/User:thomasga - results user not found

**Comment by zero-24** [comment]
> certification image links to

I have told them that but it got ignored to add some minimal validation :(

IMO just a admin can correct that links?

**Comment by jeckodevelopment** [comment]
@yvesh could you please propose a fix for it?

**Comment by zero-24** [comment]
> @yvesh could you please propose a fix for it?

What about the proposals made in the original ticket?

**Comment by yvesh** [comment]
@jeckodevelopment the fix on exams would require an API to query the user in the exams portal (and a mapping, which we both don't have).

For now it's more a question how we sanctionize his fraudulent behavior. Any input on that? :)

For all the other stuff like forum, jdocs, twitter etc. i am not sure this should be handled, it's pretty impossible to validate.

**Comment by zero-24** [comment]
> For all the other stuff like forum, jdocs, twitter etc. i am not sure this should be handled, it's pretty impossible to validate.

What about checking for "integer" for the forum thing? and explain it in the description?

The other thing can also be semi validated by require a spezific schema. Even i would suggest to use a API and disable / remove that feature until this issue is fixed / adressed.

**Comment by mandville** [comment]
"For now it's more a question how we sanctionize his fraudulent behavior. Any input on that? :)"

disable the ability to add badges ? its much like some website just copy image urls to make themselves look good and accredited 
i can find no matching user in https://exam.joomla.org/directory?search=&country=&certification=&limit=0&limitstart=0 and considering his teams he should be made aware .

**Comment by zero-24** [comment]
> disable the ability to add badges ? its much like some website just copy image urls to make themselves look good and accredited

Saddly no one cares about that it damages the brand of the "Certification" 

Let's see what happens: https://github.com/joomla/volunteers.joomla.org/pull/153

**Comment by mandville** [comment]
additional - i have been watching the new joomlers and they all appear to be incorrectly filling out their profiles. 
https://volunteers.joomla.org/joomlers/2262-patience-nekesa 
https://docs.joomla.org/User:Lpnekesa
https://forum.joomla.org/memberlist.php?mode=viewprofile&u=lpnekesa
https://exam.joomla.org/directory/user/lpnekesa
therefore it should best be disabled until such time as it works correctly or is made clearer to users

**Comment by mandville** [comment]
i see that this is still happening. still not fixed. date for disabling or fixing please.

**Comment by sanderpotjer** [comment]
Closing this one as #159 made already some changes and report button is visible for public. Link checker will added via #161
