### ISSUE TITLE
Inability to mark profiles as innacurate

### ISSUE THREAD

**Issue by mandville** [joomla/volunteers.joomla.org#159]
beyond the obvious "spammer" profiles , there is no method to mark a profile as inaccurate eg people mistakenly putting their user name in the forum link instead of their actual forum ID, or putting they are a certified administrator when they are not. 
currently the only method for review is to mark as spammer

**Comment by mandville** [comment]
#152

**Comment by sanderpotjer** [comment]
@mandville thanks for the feedback. So do you prefer a separate button or would renaming the button "spammer" to something like "report this profile" be sufficient?

**Comment by mandville** [comment]
a "general report/ review" button would be more appropriate.
