### ISSUE TITLE
Joomler Story Strips Formatting

### ISSUE THREAD

**Issue by mbabker** [joomla/volunteers.joomla.org#16]
This field is a WYSIWYG editor yet retains zero formatting.

**Comment by jeckodevelopment** [comment]
I guess that the same issue occurs also on the Report field, because Cliff report was without any formatting yesterday.

**Comment by sanderpotjer** [comment]
I guess we're talking about two different things here:
- Joomler Story on https://volunteers.joomla.org: this is on purpose, as the text is limited to XXX characters. If I use the normal `string.truncate` it places the dots `...` on the next line as it is outside the `<p>` element. Therefore the HTML is stripped, and the first characters are placed inside a paragraph tag so the dots are aligning well. 

<img width="314" alt="screen shot 2016-08-23 at 20 07 58" src="https://cloud.githubusercontent.com/assets/522834/17903908/76b6c71a-696d-11e6-809a-366bb5951029.png">
- Reports: same applies to reports on the homepage. But this is not the case for the report itself, that is allowing HTML, but it seems Cliff didn't add the link as a 'real' link.

**Comment by mbabker** [comment]
The story when you're editing your profile.  I tried to put back the one I had saved in my notes and it included a couple of links.  When I saved it all of the formatting (the links, the paragraph breaks) all got stripped out.  So I just deleted it again.

**Comment by sanderpotjer** [comment]
@mbabker ah, sorry about that... Just noticed that the "No HTML" text filter was active for the default user group. Should work now. Probably also the reason that Cliff couldn't post the link.
