### ISSUE TITLE
Advisory Board

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#160]
Hello Team,
as in the Bylaws of OSM, Section 9.10, within the Organization we need to have also the Advisory Board.
Could you please think about the implementation of such team that is not under any department, but shall serve the Full Board?

**Comment by sanderpotjer** [comment]
@jeckodevelopment sure, is not to complex. Any date that this should be ready?

**Comment by jeckodevelopment** [comment]
Thank you :)
currently we are starting to involve members, whenever is ready it will be used.

**Comment by sanderpotjer** [comment]
@jeckodevelopment should the Advisory Board be a menu-items in the horizontal site menu, or just listed among the teams on https://volunteers.joomla.org/teams?

**Comment by sanderpotjer** [comment]
>different view called "Governance" maybe in which we can display the Advisory Board, the Ombudsman

**Comment by sanderpotjer** [comment]
@jeckodevelopment this is now available on https://volunteers.joomla.org/governance (team are regular teams, but with "Board of directors" as department)

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer ;)
Awesome!
