### ISSUE TITLE
Improve "quality" of certification badge

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#161]
While waiting for the APIs of the Exam Platform, an easy way to verify whether an user is certified or not could be to check the existence of the URL, so if the answer code is 200, then the user is likely Certified. If the answer is 404 or any other code, the link to the Certified Users Directory should be dropped and no badge should be displayed.

It's a very easy and "rudimentary" way to validate the badge, but it can be useful to avoid fake badges.

**Comment by sanderpotjer** [comment]
True, but that won't prevent someone is adding a link to another user profile badge. 

The 200 check should be done on all URL's in profile, upon saving the profile for example.

**Comment by jeckodevelopment** [comment]
> True, but that won't prevent someone is adding a link to another user profile badge.

Agree, but it's pointless that someone add the link to another person's certified user. 
As said, this is not the final solution, but it's the first validation that we can do to avoid fake badges :)

**Comment by sanderpotjer** [comment]
Right now the certification is returning a 200 code, even when the link is invalid... https://exam.joomla.org/directory/user/somethingfake

So the check works for many sites now, except the certification. That needs custom adjustments in the code...

**Comment by sanderpotjer** [comment]
Links to the exam site are now checked for a valid certification profile. Other links in the profile are also checked for 200 status code if possible (some sites return a 200 code for invalid links as well...)
