### ISSUE TITLE
Automatically remove/hide "open positions" when a team is archived

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#162]
Yesterday the Certification Operations Team has been archived but the "Open Position" is still published in the Help Wanted section on the Volunteers Portal.
Shouldn't it be automatically hidden?

![immagine](https://user-images.githubusercontent.com/733133/33499373-f6c50fc2-d6d4-11e7-83cf-f464b562a932.png)

![immagine](https://user-images.githubusercontent.com/733133/33499383-02df6dc0-d6d5-11e7-8c5f-12233475eadd.png)

![immagine](https://user-images.githubusercontent.com/733133/33499387-0901b546-d6d5-11e7-996d-ee2211da3bde.png)

Thank you

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for reporting. Open positions are now automatically being archived when an end date for a team is set.

**Comment by jeckodevelopment** [comment]
Thank you
