### ISSUE TITLE
[jvols] Broken Link to JDocs website

### ISSUE THREAD

**Issue by webilicious** [joomla/volunteers.joomla.org#164]
On the https://volunteers.joomla.org/teams page in the Documentation Team (JDocs) section, there is a broken link to JDocs which should be https://docs.joomla.org/ rather than https://doc.joomla.org.
![screenshot-volunteers joomla org-2018-01-02-10-47-57](https://user-images.githubusercontent.com/5836876/34471977-78257a5a-efaa-11e7-8a4d-11133e9e554a.png)

**Comment by mbabker** [comment]
Fixed.
