### ISSUE TITLE
Replace stock image for social preview

### ISSUE THREAD

**Issue by hvdmeer** [joomla/volunteers.joomla.org#165]
When I want to share the Help wanted page to try getting some new volunteers for the teams I only see the standard "Joomla because open source matters" image in the post preview. 

Is it possible to replace this with a new one especially for either the volunteer portal or also especially for the Help wanted pages.  (The menu link and also all team pages)

**Comment by sanderpotjer** [comment]
@hvdmeer where are you sharing the link? As for the page there is already a specific image. Working on twitter & facebook at least:
<img width="545" alt="screen shot 2018-01-04 at 12 55 57" src="https://user-images.githubusercontent.com/522834/34562437-b98493c8-f14e-11e7-8d58-b2db5f45163a.png">

<img width="796" alt="screen shot 2018-01-04 at 12 55 44" src="https://user-images.githubusercontent.com/522834/34562440-bf286660-f14e-11e7-9575-b7a848b6f526.png">

**Comment by hvdmeer** [comment]
On all the official joomla accounts.  I see the stock logo when sharing the portal, the Help wanted menu link or a Roles team page. 
Since I'm posting on my phone it's difficult to share images. 

Could it be a caching on my side then?

**Comment by sanderpotjer** [comment]
@hvdmeer the help wanted page has this image set, so this URL specifically: https://volunteers.joomla.org/help-wanted

Other URL's don't have this image. So would be good to know which URL exactly you are sharing and on what social media platform, otherwise it is hard to debug

**Comment by hvdmeer** [comment]
Had to check on a test account on Twitter and I didn't test facebook before because I normally don't post on that channel.   😇
The preview is correct on facebook and Twitter but not on LinkedIn.
https://volunteers.joomla.org/help-wanted
I'll skip sharing the specific teams until I have a copy of that image for replacing the old stock one.

**Comment by sanderpotjer** [comment]
@hvdmeer LinkedIn has very aggressive caching for links that have been shared before. The solution for this is to share the link as https://volunteers.joomla.org/help-wanted?1 for example. In this way, LinkedIn will scrape the page again with the new image.

**Comment by hvdmeer** [comment]
You're just like a walking knowledge base Sander! I tried disabling/refreshing the cache in two browsers and still got the wrong image. Never knew LinkedIn is like this. Thanks
