### ISSUE TITLE
Update dummy database

### ISSUE THREAD

**Issue by brianteeman** [joomla/volunteers.joomla.org#168]
I was trying to set up a loccal copy for testing but when I try to login to the admin or frontend I get
JAuthentication: :authenticate: Failed to load plugin: plgauthenticationawoelogin

**Comment by sanderpotjer** [comment]
@brianteeman you have been using the sample database I guess. This is not maintained as nobody was using it, but will generate a new dummy dump

**Comment by brianteeman** [comment]
I was following the instructions on the readme ;)

**Comment by brianteeman** [comment]
No rush

**Comment by brianteeman** [comment]
reminder

**Comment by sanderpotjer** [comment]
@brianteeman as you said no rush I wanted to push a couple new changes first. But the dummy database is now updated and should work for local development. Thanks!

**Comment by brianteeman** [comment]
thanks
