### ISSUE TITLE
[New Feature] Add Links to StackOverflow and Joomla@StackExchange

### ISSUE THREAD

**Issue by nibra** [joomla/volunteers.joomla.org#169]
Beside our forum and Facebook pages, we have a lot of other places, where people contribute to Joomla. Most recognised among them are StackOverflow (stackexchange.com) and Joomla Q&A (joomla.stackexchange.com).

There could be a button like the one for Docs that will link to his/her profile on SO/JSE:

```
https://stackexchange.com/users/____
https://joomla.stackexchange.com/users/____
```

where `____` will be filled out by the user with his/her ID on the respective site.

These fields could be optional and the icon won't appear if the user doesn't fill out the fields with the link to his/her profile.

This is a way to recognise volunteers on these important channels.

**Comment by sanderpotjer** [comment]
@nibra thanks for your request! Should be possible to add this, we will add this to the roadmap

**Comment by zero-24** [comment]
https://github.com/joomla/volunteers.joomla.org/pull/171

**Comment by sanderpotjer** [comment]
@nibra thanks again for the suggestion and @zero-24 for the code, now on the live site
