### ISSUE TITLE
[Question] about the process to delete current Teams/Group

### ISSUE THREAD

**Issue by MATsxm** [joomla/volunteers.joomla.org#17]
Bonjour,
The concept of "sub-Teams" is really great and before I F**\* evrything doing the wrong way, I would like to know how to proceed to use it.
Currently, and talking about the JDoc, we have 2 sub Teams: **Documentation Translation Team (JDT)** and **Documentation Helpscreen Team**.
I would like then to add them as sub-Team of the main **Documentation Working Group (JDOCs)**

Could you confirm the process:
1-building the 2 sub-teams under DWG (level 2)
2-setup Members and all the stuff
3-ask you to delete the 2 teams that are at (level 1)

?
Thanks

**Comment by jeckodevelopment** [comment]
You have already Documentation Working Group (JDOCS)
just Edit the actual sub-teams and set "Documentation Working Group" as "Parent Team" if you're team leader of these sub-groups.

Otherwise, I can do it for you, since they're team under PLT responsibility

**Comment by jeckodevelopment** [comment]
Meanwhile, I did it for you :P

**Comment by MATsxm** [comment]
@jeckodevelopment 
Oh yeah... I see :+1: 
thanks!

**Comment by MATsxm** [comment]
WTF... more time to write the issue than for @jeckodevelopment to fix it :stuck_out_tongue_closed_eyes:

**Comment by jeckodevelopment** [comment]
you're welcome :)
FYI: you are in advance because PLT already planned these modifications

**Comment by sanderpotjer** [comment]
Glad you found it already :-)

Would be nice for the GSoC teams too, good to hear the PLT is working on it!

**Comment by jeckodevelopment** [comment]
@sanderpotjer for GSoC the situation is not so easy, because:
Google Summer of Code Joomla Team is under responsibility of Open Source Matters.
The GSoC sub-teams are under PLT responsibility.
Technically, GSoC after transition will become a Program, under the Program Dept.

**Comment by jeckodevelopment** [comment]
My error. It's easy.
JVols allows subteams to have different leadership team than the parent team.
So, i completed moving GSoC teams as subteams of the big GSoC Team :)
