### ISSUE TITLE
if (count($sessionQueue)) Parameter must be an array or an object that implements

### ISSUE THREAD

**Issue by ehfo0** [joomla/volunteers.joomla.org#170]
I tried to install joomla with xampp and got at the first page!
`Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\testjoomla\libraries\cms\application\cms.php on line 464
`

`	if (count($sessionQueue))
			{
				$this->_messageQueue = $sessionQueue;
				$session->set('application.queue', null);
			}`

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in "Extensions for the volunteers portal". For this Reason please close this Issue, thanks.

**Comment by ElishaOkinyi** [comment]
if (count($sessionQueue)) the error message on a website I'm working on tells me to look at the following line of code  how can it be resolved
