### ISSUE TITLE
Archived teams still on the list of teams

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#174]
If you look at Yves' profile (i know he's member of many teams), you'll spot that two archived teams are stil listed in the "membership list"
https://volunteers.joomla.org/joomlers/683-yves-hoppe

![immagine](https://user-images.githubusercontent.com/733133/36394531-05e5a43e-15b5-11e8-91ed-c9856c131272.png)

The two teams are currently archived:
https://volunteers.joomla.org/teams/gsoc-javascript-tests
https://volunteers.joomla.org/teams/gsoc-browser-tests

Thank you

**Comment by sanderpotjer** [comment]
@jeckodevelopment This was a legacy issue, before the "auto move to honour roll" feature was in place. Checked all legacy teams and should be fixed now, still many teams, but all seems to be valid ;)

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer :)
