### ISSUE TITLE
Restrict "Status" field in team page

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#178]
![immagine](https://user-images.githubusercontent.com/733133/37867463-43afd674-2f99-11e8-83cf-cf9f0aa3335f.png)

Given that the "Status" field is used to detected the type of the team in terms of voting rights where:
- **Official** means regular team with voting rights
- **Unofficial** means working group without voting rights
- **In formation** is used by teams and working groups still in the definition/recruiting phase, without voting rights.

I'd like to restrict the opportunity to change this field to the following roles:
- Department Coordinator of the Department in which the team is published
- Secretary

This will allow us to have a clear view on which teams can vote at the Board members elections.

Thank you

**Comment by sanderpotjer** [comment]
@jeckodevelopment changed now, code was already prepared for that.

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer :)
