### ISSUE TITLE
Listed twice in some teams

### ISSUE THREAD

**Issue by Sandra97** [joomla/volunteers.joomla.org#180]
Hi, 

I'm listed twice in some teams. Hopefully for the Project, I don't have yet a clone ;) 

![vp](https://user-images.githubusercontent.com/4682328/38079366-ff2cfa0a-333e-11e8-8e60-8f401316d8eb.png)

**Comment by sanderpotjer** [comment]
@Sandra97 in those cases the team lead did not set an end date for the old position, but only added a new one. 

Dates are now set, so should be good now.

**Comment by Sandra97** [comment]
Thanks Sander!
