### ISSUE TITLE
Can't login the volunteers portal

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/volunteers.joomla.org#182]
I tried to reset my password but when I click on the reset link I get a message that my user is not found...

Thanks,...

**Comment by Sandra97** [comment]
Did you try to log in with your full email address?

**Comment by coolcat-creations** [comment]
Yes, and no. I am stuck at the password reset process. I click on the reset link in the mail, put in there my mail address like the input field label says and then I get the message that my account was not found.

**Comment by sanderpotjer** [comment]
@coolcat-creations it looks like the recent downtime caused some issue, the administrator login is gone too :( Will check this later today as I can't connect to the VPN from this location.

**Comment by coolcat-creations** [comment]
Ok no worry, meanwhile teammembers can post the meeting reports. Thanks!

**Comment by sanderpotjer** [comment]
Solved via Glip-chat
