### ISSUE TITLE
can't use .us TLD

### ISSUE THREAD

**Issue by N6REJ** [joomla/volunteers.joomla.org#183]
for the last decade+ my domain has been hallhome.us
today I went to update my profile photo and it joyfully informed me that my valid domain name wasn't valid anymore lol
![image](https://user-images.githubusercontent.com/1850089/41484542-dfa8f5ca-70a2-11e8-9d58-b378d1509f8e.png)

**Comment by sanderpotjer** [comment]
@N6REJ thanks for reporting the issue. You can use .us TLD's, but the URL is returning a "503 Service Unavailable" header, and therefore the error shows up.

**Comment by N6REJ** [comment]
thats strange.. the site is up.. its in maintenance mode in J! but that shouldn't throw that header?

**Comment by mbabker** [comment]
J! throws a 503 response when in maintenance mode.

**Comment by N6REJ** [comment]
weird!
ok.. that confirms what I just saw
