### ISSUE TITLE
Joomla! Volunteers Portal error My Profile

### ISSUE THREAD

**Issue by Reijo83** [joomla/volunteers.joomla.org#184]
Hello
I have problem in Joomla! Volunteers Portal. I have account there. If i log in and i want to view my Profile (https://volunteers.joomla.org/my-profile) i get error: 
An error has occurred while processing your request. It happens to the best of us!
Don't worry! There are no bugs without a fix!

If difficulties persist, please contact the System Administrator of this site and report the error below.

404 Joomler not found
url: https://volunteers.joomla.org/joomlers/0-

**Comment by sanderpotjer** [comment]
@Reijo83 thanks for reporting the issue. It seems that somehow no Joomler profile was linked to your user account. If you login again you should be able to access your profile again.

**Comment by Reijo83** [comment]
Thanks its working now
