### ISSUE TITLE
Message about avatar on jorg homepage

### ISSUE THREAD

**Issue by Sandra97** [joomla/volunteers.joomla.org#185]
While posting a report, I noticed this message at the top: 
![index](https://user-images.githubusercontent.com/4682328/43035254-ba9634d0-8cec-11e8-99b0-cd573d7fbfac.png)

Could you please remove it? We do not display avatars in the Announcements module on jorg homepage.

Thanks.

**Comment by sanderpotjer** [comment]
@Sandra97 thanks for reporting, notice is removed.
