### ISSUE TITLE
Has my account been deleted?

### ISSUE THREAD

**Issue by lavipr** [joomla/volunteers.joomla.org#187]
I can no longer log in and the link to my profile ends with a "404 Joomler not found" error. Also, my name has been removed from the projects in which I am involved. When resetting the password (to test if this is possible at all) the message "Reset password failed: Invalid email address" appears.

**Comment by sanderpotjer** [comment]
@lavipr thank you for reporting the issue. Could you please let me know what email address you used for your account? If you prefer you can send this via [email].

**Comment by lavipr** [comment]
@sanderpotjer  Thanks for your reply. I used [email]

**Comment by sanderpotjer** [comment]
@lavipr thanks. It looks like your account has been deleted after several "spam-reports". We review the reports manually but it seems that we missed the fact your account was not a spammer account. I do apologise for this and will review what we can change to prevent this in the future. 

For now, the only option is to create a new account.

**Comment by lavipr** [comment]
@sanderpotjer ok thanks for checking. So I'll create a new account.

**Comment by zero-24** [comment]
maybe we should disable the spammer button for accounts that are part of atleast one team?

**Comment by sanderpotjer** [comment]
People seem to report others that are clearly part of a team, for unknown reasons (maybe broken link etc..). So by adding #176 we should know that better.

To solve this we need to add a check that users can't be deleted that are part of a team.

**Comment by sanderpotjer** [comment]
With the Identity Portal connected as source, this issue is no longer relevant.
