### ISSUE TITLE
Move to honor roll when the team is archived

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#188]
![immagine](https://user-images.githubusercontent.com/733133/44903253-51e56100-ad0c-11e8-9a7a-9bf36d4bc408.png)

This user looks like he's still member of the team `Marketing Product Release Management Team` but the team is currently "archived".

![immagine](https://user-images.githubusercontent.com/733133/44903301-793c2e00-ad0c-11e8-8d35-f4050f96928f.png)

User where spotted: https://volunteers.joomla.org/joomlers/1978-cyrille-poussin 

And in the team view you can see that the "End date" is properly filled with the same date as the other members.

![immagine](https://user-images.githubusercontent.com/733133/44903370-a38deb80-ad0c-11e8-8df0-2f4e9d191c59.png)

https://volunteers.joomla.org/teams/product-release-marketing-team

**Comment by sanderpotjer** [comment]
@jeckodevelopment looks like the volunteer was added twice with the same role in the past. Nowadays this is no longer possible. But due to this one of the "memberships" was ended while the other was not. Fixed this, so should be ok now!

**Comment by jeckodevelopment** [comment]
Thanks @sanderpotjer !
