### ISSUE TITLE
Issues with icomoon

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#189]
![immagine](https://user-images.githubusercontent.com/733133/45029111-e5d66600-b047-11e8-9ad0-c0f9d19fef62.png)

Can't see any of the icons in the website

![immagine](https://user-images.githubusercontent.com/733133/45029144-00104400-b048-11e8-9cb1-bf188815d865.png)

**Comment by zero-24** [comment]
This has already been reported here https://github.com/joomla/joomla-websites/issues/1223. As this seams to be a bigger issue and not related to the volunteers portal I would suggest closing here.

**Comment by jeckodevelopment** [comment]
Yes, it affects all the domains.
Thanks Tobias

**Comment by zero-24** [comment]
No not all that is the fun fact :P It works here: https://developer.joomla.org/ for example.

**Comment by jeckodevelopment** [comment]
i see the issue also there

**Comment by zero-24** [comment]
Confirmed. Looks like it was still cached somehow.
