### ISSUE TITLE
We have only one Javier!

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#19]
Besides the nice title...
in GSoC Browser Automated Test reports: https://volunteers.joomla.org/teams/gsoc-browser-tests#reports 

When someone publishes a report, as author, we can see the complete name:
`e.g. Prital Patel, Niels Braczek, Yves Hoppe`
and the we have `Javier`
![javier](https://cloud.githubusercontent.com/assets/733133/18013561/e789bb48-6bbe-11e6-8863-b5d3d7832655.PNG)

He's displayed without Last Name... but his profile shows the complete name: Javier Gomez.

Why?

**Comment by sanderpotjer** [comment]
That a bit of legacy there. In the new version of the Volunteers Portal a first and lastname is required, but in the previous version there was only one field: name. So @javigomez only filled in his firstname. As soon as he updates his profile with is lastname the "bug" will is fixed.

**Comment by jeckodevelopment** [comment]
But if you open his profile you can see his complete name:

![javi2](https://cloud.githubusercontent.com/assets/733133/18017654/e0f93c90-6bd2-11e6-9423-6c58a403e4b1.PNG)

**Comment by sanderpotjer** [comment]
In the past there were two separate input fields for the name (J! account & profile). The input is no longer separated, so from now on this can't happen anymore.

**Comment by jeckodevelopment** [comment]
So we can close this issue.
Thank you!
