### ISSUE TITLE
Report of Advisory Board displayed under the BoD section

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#190]
![immagine](https://user-images.githubusercontent.com/733133/47492583-a78e4380-d84d-11e8-9d4e-e504d9c4e165.png)

Under
https://volunteers.joomla.org/board-of-directors#reports
Report of the Advisory Board is displayed.

**Comment by sanderpotjer** [comment]
@jeckodevelopment this has been fixed, sorry for the delay!

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer  :)
