### ISSUE TITLE
[jvols] use copy to clipboard plugin for banners [enhancement]

### ISSUE THREAD

**Issue by carcam** [joomla/volunteers.joomla.org#194]
I think it will be cool to add copy to clipboard functionality to the banners page so that is a bit easier (and lots cooler) to use the banners for joomla fans.

I created a little plugin that can help on this and it was just approved by JED team: 

https://extensions.joomla.org/extension/copy-me/

I even use Joomla Banners code in the documentation to show how it works.

I do not seek recognitions, backlinks or whatever compensation you might think of I just thought it might be a nice enhancement for the page.

I was tempted to do a PR but I think it will be much messier than adding it to the site from the backend.

Anyway, please let me know if this is something we can make happen and I am available to any kind of technical request you will need for this to make it happen.

**Comment by carcam** [comment]
Hi there!! Any news about this?

**Comment by sanderpotjer** [comment]
@carcam I am sorry about the huge delay on this one. It is live now: https://volunteers.joomla.org/banners

Thanks for the nice plugin!

**Comment by carcam** [comment]
Awesome!! Glad to be helpful!! Thank you very much!!

Best!!
