### ISSUE TITLE
404 for a GSoC report

### ISSUE THREAD

**Issue by Sandra97** [joomla/volunteers.joomla.org#196]
This report goes to a 404:
https://volunteers.joomla.org/1028-gsoc-19-joomla-4-feature-enhancement-project-june-

Could you please redirect it to https://volunteers.joomla.org/teams/joomla-4-feature-enhancements/reports/1029-ds

Thanks

**Comment by jeckodevelopment** [comment]
Fixed.
there were 2 identical reports, one of them was not connected to the team properly.
Now there's only one report. Here's the link: https://volunteers.joomla.org/teams/joomla-4-feature-enhancements/reports/1028-gsoc-19-joomla-4-feature-enhancement-project-june

**Comment by Sandra97** [comment]
Thanks!
