### ISSUE TITLE
Trying to log into my account on Volunteers. Can't get in or PW reset sent. 

### ISSUE THREAD

**Issue by AlisonAMG** [joomla/volunteers.joomla.org#197]
Please describe the problem or your issue

**Comment by AlisonAMG** [comment]
Trying to log into Volunteers portal to update and report via my official CJO email login. Password in my vault isn't working. PW reset request isn't coming after an hour. 

Can anyone give this a kick?

**Comment by AlisonAMG** [comment]
Email in question alison.meeks@community.joomla.org

**Comment by sanderpotjer** [comment]
@AlisonAMG looks like your account is connected to your company email `alison@....`. Not your community email address. I can change it to your CJO email if you want.

**Comment by AlisonAMG** [comment]
Thanks Sander - I was pretty sure I had my Showcase account under alison@ and my volunteer portal report stuff under the other. Apparently not. Thanks for your reply! Much appreciated.
