### ISSUE TITLE
No Login, resetting cause "invalid verification code"

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#199]
Hey Joomlers,

I can't login using franz.wohlkoenig@community.joomla.org at https://volunteers.joomla.org/ and "Forget Password" ends with invalid verification code.

Thanks for taking Time for this
Franz

**Comment by sanderpotjer** [comment]
@franz-wohlkoenig we can't find an account under that email. I won't post the email here, but looks like you signed up with a Gmail account. Hopefully, this gives you enough info to login again.

**Comment by ghost** [comment]
Shame on me, i was sure to used the joomla.E-Mail-Addy. Thanks @sanderpotjer and sorry for wasting your time – all fine now as i can login :-)

**Comment by sanderpotjer** [comment]
@franz-wohlkoenig no problem, glad to help and good to learn all is fine now :)
