### ISSUE TITLE
[question] Who will receive email for team without an email?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#20]
The new Volunteers Portal introduced a new useful feature: Contact Team.
Well, we have in the Edit window an email field (not mandatory) where the Team Admin can write the Email address for each team... but.. what about teams without an email configured?
If the email field is not mandatory and is empty, who will receive messages sent to this team?

Is there a fallback email address? Does the Team Leader email address become the automatic recipient for his/her team?

**Comment by sanderpotjer** [comment]
If no contact email is set, the email will be send to the team leader. If the team leader is not set the mail will be send to (one of) the PLT, CLT or OSM liaisons of the team. So yes, there is a fallback system in place :)

**Comment by jeckodevelopment** [comment]
Great, thank you :)
I'm just curious about who will receive the email in PLT

**Comment by sanderpotjer** [comment]
Thats actually a good question as leadership team are all "members". Maybe best to fill in an email for PLT in the settings? Did the same for the CLT.

**Comment by jeckodevelopment** [comment]
the fact is that PLT doesn't have a group email... or better, we have one but is a private list.
We need another one

**Comment by sanderpotjer** [comment]
Bit of a side-note, but the CLT opened our list for public writing a while ago, so we didn't need another one.

**Comment by jeckodevelopment** [comment]
I tried to contact the PLT and Matt Baylor  (JED) received my message. I guess we have a problem here

**Comment by sanderpotjer** [comment]
@jeckodevelopment thats indeed a problem, thanks for checking. Issue is fixed.

**Comment by jeckodevelopment** [comment]
Thank you
