### ISSUE TITLE
Reporting a profile

### ISSUE THREAD

**Issue by brianteeman** [joomla/volunteers.joomla.org#200]
Is it correct that I do not need to be authenticated to report a profile? I would have expected it to require a login

**Comment by sanderpotjer** [comment]
@brianteeman that is correct. It was after authentication in the past, but to make it easier to report that changed. Reports are reviews, so never automatically processed. And soon a motivation for a report will be required, as it is not always clear why a profile is reported.

**Comment by brianteeman** [comment]
OK - was just surprised and wanted to double check it was intentional
