### ISSUE TITLE
Volunteers are twice in the overview

### ISSUE THREAD

**Issue by bembelimen** [joomla/volunteers.joomla.org#202]
In the list overview a person is listed twice:
![grafik](https://user-images.githubusercontent.com/1229869/65388858-158a0600-dd50-11e9-9441-0ac2bd1c649f.png)

https://volunteers.joomla.org/teams/joomla-enhancement-development-team (click the tab "subteams")

While in the details view, she is only available once (which is correct):

![grafik](https://user-images.githubusercontent.com/1229869/65388866-28043f80-dd50-11e9-9d15-fcbb9f968686.png)

https://volunteers.joomla.org/teams/page-builder-working-group

I think the reason is, that she is moved from normal member to team lead.

**Comment by sanderpotjer** [comment]
@bembelimen looks like the member role wasn't "ended" by setting an end date. I have now done this for the member role, so she is no longer showing up twice.
