### ISSUE TITLE
Include identity.joomla.org feature/gdpr

### ISSUE THREAD

**Issue by Alcaeusd** [joomla/volunteers.joomla.org#203]
The identity.joomla.org property must be included in `feature/gdpr` branch in `www/templates/joomla/helpers/template.php` , with a GTM Id and ccCategories Performance and Functionality as true.

**Comment by sanderpotjer** [comment]
@Alcaeusd property is added, but need GTM code to complete. @jeckodevelopment can you help us with that?

**Comment by jeckodevelopment** [comment]
@Joomv can you please provide a new GTM code?
