### ISSUE TITLE
Elections Tools for Secretary

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#210]
Hi :)
finally i found the time to detail all the requirements of the export tools needed by the Secretary to deal properly with the elections, without becoming crazy.
Thank you in advance

### As Secretary I would like to have a set of filters in the Volunteers Portal to extract a list of the volunteers to be used for the elections.
1) The extracted lists should include for each member: Full Name, Email Address, Role, Team
2) The filters should allow to: 
a) include/exclude team members
b) include/exclude team contributors
c) choose which team list view/export
d) choose the department
e) include/exclude teams by their status (Official, In Formation, Unofficial)
3) The extracted list should be visible on the screen (backend)
4) The extracted list should be exportable as CSV

### As Secretary I would like to have the chance to send a message (text or html-formatted) to all volunteers, selecting them by certain parameters:
1) Selecting Department(s)
2) Adding/Removing Teams 
3) Filtering Teams by Status (Official, In Formation, Unofficial)
4) Filtering Volunteers by Role/Class (Contributors, Members, Team Leaders, Directors, Officers).

A use case scenario is sending the invitation for the Semi-Annual Members Meeting that, according to the Bylaws should be sent only to "Members" (Class 1, 2 and 3) of OSM and with the current messaging system has been sent also to volunteers that are enrolled as contributors in any teams.

I'm available to provide any further information needed.

Thanks!

**Comment by sanderpotjer** [comment]
@jeckodevelopment Hi Luca, please have a look at the backend "Members" view:
<img width="1673" alt="Screenshot 2020-01-25 at 17 46 54" src="https://user-images.githubusercontent.com/522834/73124366-da683f80-3f9a-11ea-9ad9-b230d92898f0.png">

- New filters have been added to allow you to make specific selections (members, contributors, team roles etc..) 
- By clicking "Export current selection (CSV)" in the toolbar you can export the active selected list
- By clicking "E-mail current selection" you will be able to send an email to the active selected list

Hopefully, these changes will make it much easier for you :)

You can check this in the backend, let me know if additional changes/filters are needed.

**Comment by jeckodevelopment** [comment]
Hi @sanderpotjer ,
thank you very much for these export tools, I could save a lot of time with them!

The only thing that doesn't work is "Board of Directors".
If you filted by "Board of Directors" as "Department" then you can see only people from "Ombudsman" and "Advisory Board" teams. Officers and DCs are not shown.

Not a big issue, but maybe that's because of the BoD being a "special" dept. in the JVP.

Thanks

**Comment by sanderpotjer** [comment]
@jeckodevelopment glad to hear it saved a lot of time! Made a small change, so it is now loading the board of directors members.

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer !
This has been really useful! :)
I guess we can close this issue as resolved!
