### ISSUE TITLE
  COM_VOLUNTEERS_REGISTRATION_SAVE_FAILED

### ISSUE THREAD

**Issue by acvmultimedia** [joomla/volunteers.joomla.org#218]
Hello,

When I try to join in https://volunteers.joomla.org/register, I can´t save the changes:

Warning

COM_VOLUNTEERS_REGISTRATION_SAVE_FAILED

Thanks

**Comment by sanderpotjer** [comment]
@acvmultimedia 
Hi Josean, at the moment I'm not able to replicate the issue. Can you otherwise reach out to me on Glip our by mail: sander.potjer [aaat] community.joomla.org with the data you fill in the fields, looks like it is somehow related to that.

Thanks! Sander

**Comment by acvmultimedia** [comment]
I've already done it but at the third opportunity and with Google Chrome. Firefox was giving me the bug.

**Comment by acvmultimedia** [comment]
Thanks @sanderpotjer
