### ISSUE TITLE
No Login after Registration

### ISSUE THREAD

**Issue by blancanieve** [joomla/volunteers.joomla.org#219]
Hi there,

I tried to register as a volunteer. Even though the registration seems to be successful, I cannot log in afterwards (I get the message "Email and password do not match or you do not have an account yet."). When I try to reset the password, it doesn't find my email address (the one I just used for registering). 
I tried several times, but it doesn't seem to work.
Please advise.

Thanks, Nadine

**Comment by sanderpotjer** [comment]
@blancanieve hi Nadine, did you received a confirmation email after registration? I can't find an account in the system, so looks like the registration was not successful.

**Comment by blancanieve** [comment]
Hi Sander, no, I did not receive a confirmation email. But on the website I received the message that registration was successful and that I can log in.

**Comment by blancanieve** [comment]
Hi again, 
I tried again a minute ago and now it worked :-) 

I will close that issue now.
Thanks,
Nadine
