### ISSUE TITLE
Improve privacy management in Mass mail of the Volunteers Portal

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#224]
Hello,
I used the Mass Email feature of the Volunteers Portal to send out the OSM Semi-Annual Meeting invitation, selecting all the active members of official teams.

This feature is very useful, but it has a "**privacy flaw**", putting all the recipients in the "**to**" field.
It would be better to have the recipients in the "**bcc**" field.

Having them in the To field led also to have the mail coming in the spam folder because of one of the classic spam patterns.

Thank you

**Comment by sanderpotjer** [comment]
@jeckodevelopment made the requested changes and some others that should reduce the spam marking.

**Comment by jeckodevelopment** [comment]
Thank you!!
