### ISSUE TITLE
Improve mail deliverability of JVP

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#225]
Hello,
can you please check and eventually fix the SPF record for volunteers.joomla.org
Emails sent through the portal come to the Spam folder.
SPF should help, given that now they come with a "soft-fail":

`Received-SPF: softfail (google.com: domain of transitioning no-reply@joomla.org does not designate 72.29.124.152 as permitted sender) client-ip=72.29.124.152;
Authentication-Results: mx.google.com;
       spf=softfail (google.com: domain of transitioning no-reply@joomla.org does not designate 72.29.124.152 as permitted sender) smtp.mailfrom=no-reply@joomla.org
Received: from volj by joomla-misc.directrouter.com with local (Exim 4.92) (envelope-from <no-reply@joomla.org>)`

Implementing the DKIM and DMARC record through cPanel would improve deliverability too:
https://docs.cpanel.net/knowledge-base/email/how-to-keep-your-email-out-of-the-spam-folder/ 

Thank you

**Comment by sanderpotjer** [comment]
@jeckodevelopment need to check if we can access the DNS. Usually, these type of requests are done at Rochen directly.

**Comment by jeckodevelopment** [comment]
Ok, thanks!
You have the permissions to open tickets, right?
Let me know if there is anything i can help with

**Comment by sanderpotjer** [comment]
@jeckodevelopment ticket submitted at Rochen.

**Comment by sanderpotjer** [comment]
Rochen did the SPF changes. So should be better now.

**Comment by jeckodevelopment** [comment]
Thank you! 
Let's close for now, we'll see next time i'll send emails :)
