### ISSUE TITLE
Filtering for volunteers

### ISSUE THREAD

**Issue by bembelimen** [joomla/volunteers.joomla.org#226]
Not sure, how the filters works, but this looks a bit strange to me: https://volunteers.joomla.org/joomlers?filter_search=Frank

**Comment by hvdmeer** [comment]
His introduction, I guess the filter also searches there

> I am a designer and Joomla enthusiast since 1.5. I support the German community with graphic design, speeches at Joomla events such as Joomla Day and J and Beyond and organize the Joomla User Group __**Frank**__ furt. Beside my passion for design and Joomla I am driven by health topics and nature protection.

**Comment by bembelimen** [comment]
OK, thanks, perhaps it should be changed in the future? At least it's not my expected behaviour.
But now as I know it, I can handle it :)

**Comment by wilsonge** [comment]
Intro and Joomla story :) https://github.com/joomla/volunteers.joomla.org/blob/master/www/plugins/search/volunteers_volunteers/volunteers_volunteers.php#L69-L71

**Comment by sanderpotjer** [comment]
@bembelimen Joomler search is now limited to names only. Thanks for the suggestion!
