### ISSUE TITLE
[jvols] ordering in honour roll

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/volunteers.joomla.org#227]
If I am not wrong the ordering of volunteers in the honour roll seems to be alphabetical. I think in that case it would be better to order it by date (started/ended). 

Hope it makes sense. 
Thanks for doing an awesome job. 

Regards,
Radek

**Comment by sanderpotjer** [comment]
@Radek-Suski thanks for the suggestion. The honour roll is now sorted by date ended.

**Comment by Radek-Suski** [comment]
Awesome. Thank you very much @sanderpotjer 
As always, I am very thankful for your and your team job
