### ISSUE TITLE
Google+

### ISSUE THREAD

**Issue by Sandra97** [joomla/volunteers.joomla.org#228]
Please remove sharing on Google+
It has been closed nearly one year ago.

**Comment by sanderpotjer** [comment]
@Sandra97 can you be more specific? Has been removed from the profiles a while ago

**Comment by Sandra97** [comment]
It's still displayed on reports.
For example https://volunteers.joomla.org/teams/accessibility-team/reports/1173-team-meeting-19th-february-2020

**Comment by sanderpotjer** [comment]
@Sandra97 from your initial issue report it was not clear you were talking about the sharing of reports, so thanks for the details. Will look into it.

**Comment by Sandra97** [comment]
Thanks!

**Comment by sanderpotjer** [comment]
@Sandra97 Google+ is no longer visible, thanks for the report!
