### ISSUE TITLE
profile website not validating

### ISSUE THREAD

**Issue by davidsteadson** [joomla/volunteers.joomla.org#229]
When editing my user profile, it is reporting my site www.tribetech.net as not valid. I have tried with and without https:// and http:// as well as with and without trailing /

**Comment by sanderpotjer** [comment]
@davidsteadson  https://www.tribetech.net/ is returning a 301 status, https://www.tribetech.net/index.php/en/ a 503. If you enter a ulrl with a valid 200 status response it will work.

**Comment by davidsteadson** [comment]
fair enough on a 503, but probably should accept 301s

**Comment by sanderpotjer** [comment]
@davidsteadson accepting 301 status now, as a test. Hopefully, it doesn't result in a lot of moderation :-) Thanks for the report!
