### ISSUE TITLE
[jvols] language string

### ISSUE THREAD

**Issue by brianteeman** [joomla/volunteers.joomla.org#23]
When you send a message the response is not in correct english

it says

"your message is send"

I would do a PR but I dont see any language strings in the repo for this component

**Comment by jeckodevelopment** [comment]
It should be "your message has been sent", right?

**Comment by brianteeman** [comment]
yes - found the language file now and doing a PR to fix that and other strings

**Comment by jeckodevelopment** [comment]
already done #24

**Comment by brianteeman** [comment]
shoot - i am doing a much bigger PR - lots of changes - it will overwrite yours

**Comment by jeckodevelopment** [comment]
you're killing my baby PR!

**Comment by jeckodevelopment** [comment]
@brianteeman when you're done, just close mine.

**Comment by brianteeman** [comment]
done
