### ISSUE TITLE
"Vulnerability : Broken Authentication(ACCOUNT TAKEOVER)"

### ISSUE THREAD

**Issue by mahadalifazil** [joomla/volunteers.joomla.org#230]
HI Team
I am a security Researcher and i found following vulnerability in your website:

https://www.cryptohopper.com/ 

Weakness: Improper Authentication - Generic
Vulnerability : Broken Authentication(ACCOUNT TAKEOVER)

Steps to reproduce:
1) Create an account having email "123@c.com".
2) Now Logout and ask for password reset link. Don't use the password reset link sent to your mail address.
3) Login using the same password back and update your email to "672@c.com".
4) Now logout and use the password reset link which was mailed to "123@c.com" in step 2.
5) Password successfully changed.
6) Boom!!

All previous password reset links should automatically expire once a user changes his email.

Impact:
1) My email account is compromised. Attacker asks for password reset link for my account.
2) I change my email address on my  account. I think i am safe now.
3) But the hacker can still use the old password reset links (which he had never used for single time) which were sent to my old email address.
4) My account is now compromised again. 

Waiting for your early response and hopefully  $200  bounty for responsibly reporting this vulnerability reports.

kindly contact me on this email : mahadalisecurehaker@gmail.com

Regards,
Mahad Ali

**Comment by wilsonge** [comment]
Thanks for your report. This is a publicly available issue in the CMS which has been known about for over 18 months https://github.com/joomla/joomla-cms/pull/22843 

You can find more information there. Closing this issue
