### ISSUE TITLE
Order the Department Coordinators list in Dept. View

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#234]
Hello,
when there is a Department Leadership team published in the Volunteers Portal, the list should be ordered to show as first the **Department Coordinator** and as second the **Assistant to the Department Coordinator**. After them, the list of any eventual "Department Member".

https://volunteers.joomla.org/departments/production 

If you look at Production, the list shows the DC after several positions in the list.

Thank you

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for reporting the issue, fixed now.

**Comment by jeckodevelopment** [comment]
Thank you!
