### ISSUE TITLE
Problems with form registration

### ISSUE THREAD

**Issue by acvmultimedia** [joomla/volunteers.joomla.org#235]
My associate[removed] wants to become a volunteer and has been trying to do so for more than 5 tries and she can't.

She gets a message that the user is recorded and created but then cannot access it. If she retrieves the password she says the email doesn't exist...

**Comment by sanderpotjer** [comment]
@acvmultimedia does she fill in all fields? Can she please try to only fill in the required fields and see if it works in that case?

**Comment by acvmultimedia** [comment]
She has already tried, the thing is that she does tell you that she has saved but then the user does not exist.

**Comment by acvmultimedia** [comment]
An email has just arrived at 13:08 with the notification that the user is registered [removed]

Is it casual? Or have you done something?

THANK YOU!!

**Comment by sanderpotjer** [comment]
@acvmultimedia that was me :) Testing the signup and worked for me, so seems to be something very specific (maybe browser plugin filling fields automatically?). I did send an email with the login details.

**Comment by acvmultimedia** [comment]
I'd say no to the plug-in stuffing, but maybe. Anyway we register in many other pages and it never happens to us... it's something strange.

Thank you very much.
