### ISSUE TITLE
Subteams aren't marked as unofficial when the parent teams are

### ISSUE THREAD

**Issue by wilsonge** [joomla/volunteers.joomla.org#236]
https://volunteers.joomla.org/teams/joomla-4-working-group Is apparently still an official group despite the fact that the parent team is marked as archived and thus unofficial. Presumably when a team is archived then all subteams should be too?

**Comment by sanderpotjer** [comment]
@wilsonge thanks for reporting. There is currently no automatic process in place for that. However, two clicks for the team leader when team is ended. Changed it now.
