### ISSUE TITLE
[Field] - NDA Signed date field

### ISSUE THREAD

**Issue by conconnl** [joomla/volunteers.joomla.org#239]
Members within our organization are required to sign the NDA, as our manual registration process has failed us on different moments, we would like to have a field for the JVP Members where the NDA signed date can be registered.

The field doesn't have to be visible for anybody visiting a department, team or member.
It should at least be editable by the Secretary (DPO) and the (Assistant) Department Coordinators as they are responsible in the first place to make sure the NDA is signed.

What do you need from me, @jeckodevelopment or other board members to make this possible?

**Comment by sanderpotjer** [comment]
Something similar has been build in the past for CoC:
<img width="430" alt="Screenshot 2020-05-22 at 09 07 01" src="https://user-images.githubusercontent.com/522834/82640865-a5e45780-9c0b-11ea-97df-d7a68e618d2b.png">

https://github.com/joomla/volunteers.joomla.org/issues/110

I've spend quite some time on that, but never been in use. What is different this time? How can we prevent time spend on feature that is not used?

I also wonder if JVP is the correct place for this. Maybe it should be within the IDP, but in that case only the secretary can manage it.

**Comment by conconnl** [comment]
I have read the thread, a interesting discussion.
What I got out of it, that the CoC signing is for users on the JVP who are members of a team and could be done the same as privacy consent by letting them place the check mark and not the Secretary.

As you have implemented it as "Set by Secretary only", this could possibly be changed to "Set by Secretary & DCs" then a date field can be added for the NDA sign action.
I totally understand the reservation and the question if the JVP is the right place, I would agree with using the IDP if the DCs also can manage it.
I personally don't think it's smart to just let one person handle it, especially if that person already has a lot to do and because the DCs are responsible for NDA sign actions.

The NDA is a legal document, which can change for various important reason.
Therefore a data is important to be able to generate a report and send the volunteers a mail with the request to sign it again. This is different with an CoC.
We also have the JEDCA and possibly others in the future.

You are much better in these things, we basically need a central registration connected to the user. If this for example means a small form input page on the IDP where you can select the type of agreement, the user and the date to register. Where the form add it to the user data, this also a solution.

**Comment by sanderpotjer** [comment]
@conconnl the downside of using JVP for the "central registration" is that this will be available on the JVP only. It won't be possible in the future for another property site to display certain functionality for users that signed the NDA. If the Identity Portal is used for this as central location other sites will be able to check that field as well. 

A potential downside of the Identity approach is that we need to create management functionalities in there. 

The NDA seems to be an Adobe sign form, isn't that received by the secretary already? Or is that send to all DC's? If only the secretary receives it the work for the management feature makes no sense. Of course, we can make the field visible for the DC's in the volunteer portal to see if people signed it or not.

**Comment by jeckodevelopment** [comment]
The NDA signing flow is:
- The party goes to EchoSign to sign the DNA
- The NDA is sent to president@opensourcematters.org for signature
- Once countersigned by the president, it goes to secretary for "approval" (that is a signature to keep track of it and archive it). So it's already received by the secretary. 

A date field in which I can record the signature date would be enough (imho), and I'd keep it on the JVP, as it has been defined as the Volunteers Registry

**Comment by conconnl** [comment]
Having it on Identity brings other possibilities for in the future.
Like the DPA registration.
Yes we need a management option in the future, but as the registration is done by the Secretary at the moment, do we really need a tool at this moment instead of just access to the backend. (I don't know the technical impact).

**Comment by conconnl** [comment]
What do we need to do, to make a decision and implementation plan?

**Comment by conconnl** [comment]
What can we do to move forward with this?

At one side the registration option and on the other side the ability for DCs and officers to see if someone indeed signed the NDA (In future DPA and others)
We can do it in phases off course, that for example I need to support the Secretary to fill the data.

I would say:
* Use the IDP website
* A view / table where we can select the user, select a date and pre-configured document type (NDA, DPA, etc)
* Registration in the backed is enough, with a little bit of ACL we can give a person access.
* Frontend User Profile page display, show the documents they signed and when.

Something to show the members with access to team management on the JVP, that a user signed X documents.
Like the address checkmark.

**Comment by sanderpotjer** [comment]
We first have to make sure the IDP part is ready, issue for that: https://github.com/joomla/identity.joomla.org/issues/102

**Comment by sanderpotjer** [comment]
@conconnl now the IDP is completed: does a checkmark needs to be visible for every type of document, or just specific ones for team management?

**Comment by conconnl** [comment]
> @conconnl now the IDP is completed: does a checkmark needs to be visible for every type of document, or just specific ones for team management?

That is a very good question.
I would think not all of them, but possibly configurable.
Especially if more documents are added in the future.
As it's partly legal it would be better to know what Luca thinks.

@jeckodevelopment please tell you what is required to display and what can be just a registration.
I would say at least the NDA.

**Comment by JazParkyn** [comment]
Being able to see who has signed the NDA or not is probably the most useful

**Comment by jeckodevelopment** [comment]
sorry for the late reply on this. I missed a ton of notifications.
I would say that it would be useful if Board members (Officers+DCs) can see whether someone signed the NDA or not.
This would speed up the check, without having the secretary to check the signature.

**Comment by sanderpotjer** [comment]
@jeckodevelopment @conconnl @JazParkyn this is now available on the JVP side as well. People able to "edit" a team in the JVP will be able to see the column "NDA" and it will be checked if the document is signed. After saving a document in IDP the JVP site will be pinged and updated automatically. 

<img width="422" alt="Screenshot 2021-02-15 at 23 49 41" src="https://user-images.githubusercontent.com/522834/107999891-edf0a900-6fe8-11eb-9223-9c4aa72272fc.png">

All current signed documents info is pinged to the JVP, so should be in line with the signed documents in the IDP.
