### ISSUE TITLE
Mark volunteers profile when deceased

### ISSUE THREAD

**Issue by hvdmeer** [joomla/volunteers.joomla.org#240]
Sadly there cases that a Joomler passes away. I would suggest to mark their volunteer profile with the status Passed away and/or add a black ribbon on the profile picture.

**Comment by sanderpotjer** [comment]
@hvdmeer I like the idea, but not sure what the OSM board thinks of that, in the past we have had request to delete profiles directly. This will be temporary anyway, as profiles will automatically be anonymized as the consent for data usage won't be renewed.

**Comment by jeckodevelopment** [comment]
From the legal perspective, their OSM membership is terminated upon death.
So their profile would be listed with the honor roll tab as first (given that they can't have any active team membership) and will be anonymized when the consent expires.

**Comment by hvdmeer** [comment]
So if I search for a member on the Joomlers tab the profile will be almost empty? 
But indeed there are perhaps legal issues.

I'm not sure if anyone would care for a black ribbon on their profile when they pass away and it's not something one would think about on a normal day.

Is this something that should be discussed on a GDPR level or a OSM board level?

**Comment by jeckodevelopment** [comment]
About the termination of membership, it's written in the bylaws:
Section 4.04(A)(5).

We need to check on the GDPR level first

**Comment by mandville** [comment]
for gdpr 
"Information relating to a deceased person does not constitute personal data and therefore is not subject to the GDPR."

**Comment by OnTheMarkDesign** [comment]
Correct word is "Deceased" NOT "diseased" https://www.merriam-webster.com/dictionary/deceased

**Comment by hvdmeer** [comment]
But is this something worth implementing @jeckodevelopment ?

**Comment by jeckodevelopment** [comment]
i don't have anything against it.
I was only thinking that, when their consent expire (after 1 year of the renewal of consent), their profile gets anonymized.
What are your thoughts? @sanderpotjer @conconnl @roland-d ?

**Comment by mandville** [comment]
again consent expires at time of death

**Comment by roland-d** [comment]
You cannot really search for any deceased persons because their profile will be anonymous. Unless you can deduct from their involvement who they were.

Consents that are not renewed automatically expire and as such their info will be anonymized.

**Comment by conconnl** [comment]
I wouldn’t take to much effort to create something for this, in general when consent isn’t extended you can’t show the information anymore, no matter the reason that it’s not extended. 

In case of dead, your consent expires as there is no legal bases anymore, if your consent would expire a few days after you died, what is the purpose of showing anonymized data with a badge or whatever that he/she died.

**Comment by sanderpotjer** [comment]
As profiles are anonymized on consent expiration we won't add anything specifically for this.
