### ISSUE TITLE
Volunteers.Joomla.org - Help wanted page- Add a button with 'learn more’/ ‘contact'

### ISSUE THREAD

**Issue by davidemessia** [joomla/volunteers.joomla.org#242]
Hi,
in the https://volunteers.joomla.org/help-wanted 
it's possible to Add something on the Right to ‘learn more’, or ‘contact’, easy contact page that can get you to :
- The ‘head’ of volunteer engagement
- The Team Leader of the group that opened the position

thanks a lot
Best regard
Davide

**Comment by sanderpotjer** [comment]
@davidemessia thanks for the request, button is added.
