### ISSUE TITLE
[Feature Idea] Add ID's to sections so that hyperlinks to groups of listings can be added

### ISSUE THREAD

**Issue by particthistle** [joomla/volunteers.joomla.org#243]
Just writing some JCM articles, and wanting to cross promote some job listings on https://volunteers.joomla.org/help-wanted

However, at the moment I can only send readers to https://volunteers.joomla.org/help-wanted and not to a section of the page as there's no id values in the sections to create bookmark links through to.

For example, I want to link to positions in the Joomla! Enhancement Development Team in an article on the Joomla 4 Media Manager, so would be able to use:
https://volunteers.joomla.org/help-wanted#Joomla-Enhancement-Development-Team if there was an ID set with the value Joomla-Enhancement-Development-Team

Additionally, that could be used to build a table of contents on the Help Wanted page.

**Comment by conconnl** [comment]
Thanks for the suggestion. 
The code has added to the repo and will be released shortly in the live site.
