### ISSUE TITLE
[Feature Idea] Extra tab in profile to allow volunteers to record their local JUG involvement

### ISSUE THREAD

**Issue by particthistle** [joomla/volunteers.joomla.org#244]
### To allow Joomlers to show their local Joomla involvement (eg Joomla User Groups, JoomlaDay Organising committees, Joomladay Speakers local membership, local joomladay attendance) it would be good to have some tabs to show that information.

**My local Joomla involvement** tab
Allows you to log participation in 
- Joomla User Groups
- JoomlaDay Organising Committees
- Speaker History

**Suggested Fields:**
- Organisation / Event = Text
- Type = Select List: Joomla User Group, Joomla!Day Conference, Joomla! World Conference, Presentations
- Position = Select list (TBD): Organiser, Co-Organiser, Speaker, Team Member, Member, Attendee: Filter for sub set based on event
- Start Date = Date (required)
- End Date = Date (optional: blank = Present)
- Information = Textarea (protected): Allows Joomler to put details in about their involvement.
- Link = For Speaker history, there could also be a field for Presentation links to link through to youtube videos, slideshares or pages on Joomla!Day sites. (Would be a protected link field indicating you're about to open an external page).

_Discuss!_

**Comment by particthistle** [comment]
Discussion also occurring in Ringcentral JUG Leader Working Group channel.

**Comment by jeckodevelopment** [comment]
The Volunteers Portal is the official registry of OSM members.
I wouldn't add too many fields and data.

**Comment by conconnl** [comment]
Most of the information is already on the relevant locations like the Events/Jugs Directory.
Which is maintained, checked, etc by the related team.
This suggestion reads as duplication of information, which is already displayed in the Events/Jugs Directory.
If the events directory misses certain information, like a button to define you are attending a JUG meeting it's something which can be discussed with that specific team.

Events has not much to do with the Joomla (OSM) volunteers and the purpose of the website.
There are already a multitude of possibilities to link to your own social profile pages, where you can display links to all types of social, video, presentation types of information.

Adding a field to show a link to your JUG Listing page on the (new) JUGS Directory in the future, is something small and an option I can imagine it helps with showing more information. Duplication of information just increases efforts, maintenance, the need for checks etc.

**Comment by jeckodevelopment** [comment]
Something similar is being discussed in WordPress too: 
https://make.wordpress.org/community/2020/07/03/proposal-recognition-for-event-volunteers-and-attendees-in-wordpress-org-profile/

**Comment by sanderpotjer** [comment]
Partly this has been added by the new "Groups" page which list the JUG Organizers: https://volunteers.joomla.org/groups/user-group-organizers

@conconnl maybe in line with this also create groups for JoomlaDay Organisers etc.. like Patrick suggested above? 

Another thing would be good to make clear how users can make sure they are added? Maybe in description or get involved tab at least?

**Comment by conconnl** [comment]
Correct, I haven't yet received any suggestion from the JUG Team or others in the department to add a description or information in the other tabs, as well not a list of people to add.
For the JDay Organizers it was suggested as well to create the group, still waiting on confirmation.

The feature idea has been processed and the Department / Team knows where to go to extend it.
