### ISSUE TITLE
Remove non confirmed user from the "Add Joomler" list

### ISSUE THREAD

**Issue by bembelimen** [joomla/volunteers.joomla.org#248]
Hello,

when adding a new Joomlers to a team the list is now flooded by "Guests":
![grafik](https://user-images.githubusercontent.com/1229869/91955101-fab36600-ed02-11ea-9849-ded7230713f8.png)

Probably we could filter them out?

**Comment by sanderpotjer** [comment]
@bembelimen thanks, guests are no longer listed in this dropdown.
