### ISSUE TITLE
[BUG] - Joomla RSSB - Recursion

### ISSUE THREAD

**Issue by conconnl** [joomla/volunteers.joomla.org#249]
Please implement the fix done in the RSSB plugin, so recursion stops creating unnecessary short urls in our system.
https://github.com/joomla-projects/plg_content_joomlarrssb/blob/master/joomlarrssb.php#L329-L356

**Comment by sanderpotjer** [comment]
@conconnl fixed, see https://github.com/joomla/volunteers.joomla.org/commit/2422e8e65917edf73ef1f5e0dac87923a87233f2

**Comment by conconnl** [comment]
Thank you very much
