### ISSUE TITLE
[jvols] Can't login

### ISSUE THREAD

**Issue by JeroenMoolenschot** [joomla/volunteers.joomla.org#250]
login button gives this error:

Unhandled exception
An unhandled exception was thrown.

If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:

f3543de1c0

How to get help

This error probably is due to some unexpected behaviour or to misconfiguration of SimpleSAMLphp. Contact the administrator of this login service, and send them the error message above.

**Comment by sanderpotjer** [comment]
@roland-d can you have a look?

**Comment by JeroenMoolenschot** [comment]
i cleaned my browser-cache and it seem to work now. Maybe it was a problem on my end.
