### ISSUE TITLE
[Team Labels] - Change "Unofficial" to "Working Group"

### ISSUE THREAD

**Issue by conconnl** [joomla/volunteers.joomla.org#252]
Discussed with @jeckodevelopment 

All teams on the JVP are official in relation to our organization.
The JVP uses the labels "Official", "In Formation" and "Unofficial", the latter is used for Working Groups.
Teams which are official but do not having voting rights and do not have to follow certain team rules.
We don't have any unofficial teams on the JVP.

Please change the label accordingly.

**Comment by jeckodevelopment** [comment]
This wording change would improve also the understanding of the "rights & obligations" by teams/working group, answering some of the recurring questions asked during the voting periods.

**Comment by sanderpotjer** [comment]
@conconnl @jeckodevelopment label changed, see for example https://volunteers.joomla.org/teams/conflict-resolution-team

**Comment by conconnl** [comment]
Thank you very much
