### ISSUE TITLE
Typing Issue - User Research & Strategy Group

### ISSUE THREAD

**Issue by aboarken** [joomla/volunteers.joomla.org#257]
The group information should be updated. Please check the attached picture for further information.

![Issue](https://user-images.githubusercontent.com/18500882/111082747-e5718c80-851a-11eb-8956-de6dc99d7648.jpg)

**Comment by conconnl** [comment]
Thanks,
I guess you mean that it isn't wrapped to the next row.
I changed that, the contact button can be used to contact a team if you have an suggestion for them.

**Comment by aboarken** [comment]
> Thanks,
> I guess you mean that it isn't wrapped to the next row.
> I changed that, the contact button can be used to contact a team if you have an suggestion for them.

Thank you @conconnl
