### ISSUE TITLE
Switch "Governance" menu to "Groups"

### ISSUE THREAD

**Issue by conconnl** [joomla/volunteers.joomla.org#258]
The "Governance" menu item has been changed too "Groups" in the backend.
To be able to show more additional groups which are not part of the membership structure but makes it possible to do more recognition for various groups.

A htaccess rule has been added for redirect:
```
# Redirect Governance too groups
RewriteRule ^governance(.*)$ /groups$1 [R=301,L]
```

A language override has been added:
COM_VOLUNTEERS_TITLE_GOVERNANCE="Groups"

Possibly we need to reflect the changes also in the PHP code to decrease future confusion.
I think teams.php (models) // view.html.php (teams view) // default.php (teams view)

**Comment by sanderpotjer** [comment]
@conconnl Thanks Wilco, changes in code have been done.
