### ISSUE TITLE
Forward from old plt to production

### ISSUE THREAD

**Issue by rdeutz** [joomla/volunteers.joomla.org#259]
The old link from the PLT is still there https://volunteers.joomla.org/departments/production-leadership-team. Can we make a redirect to https://volunteers.joomla.org/departments/production to avoid confusion in the future. See https://github.com/joomla/joomla-cms/pull/33390#issuecomment-828404259

Thanks in advance

**Comment by sanderpotjer** [comment]
@rdeutz thanks for the heads up, redirect is now in place.
