### ISSUE TITLE
Google Maps javascript error on profile

### ISSUE THREAD

**Issue by hans2103** [joomla/volunteers.joomla.org#260]
There is an error with Google Maps API causing the Map not rendering on https://identity.joomla.org/profile

<img width="1146" alt="Schermafbeelding 2021-05-14 om 21 45 16" src="https://user-images.githubusercontent.com/639822/118321293-b321e280-b4fd-11eb-9036-07bedc428c54.png">

https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
> The current URL loading the Maps JavaScript API has not been added to the list of allowed referrers. Please check the referrer settings of your API key in the Cloud Console.

**Comment by particthistle** [comment]
As @hans2103 pointed out, RefererNotAllowedMapError looks to just be a case of:

- adding identity.joomla.org to the referer list for the Google Maps API Key
- adding Joomla's Google Maps API key to identity.google.com if it's not already been done.

@roland-d @sanderpotjer is this your task, or something you need to escalate to @conconnl?

**Comment by sanderpotjer** [comment]
I can't access the settings. Hopefully @conconnl can.

**Comment by conconnl** [comment]
Where should I look to find any of these settings?
I personally never use Google Maps, for what I have heard you even need a creditcard.

**Comment by roland-d** [comment]
@conconnl This is to be setup in the Joomla Google account: https://console.cloud.google.com

Perhaps @jeckodevelopment needs to do this?

**Comment by conconnl** [comment]
Ahh, that is the place where the VPN VM is running.

**Comment by conconnl** [comment]
There is no project, configuration or whatsoever for Google Maps.
Which one do we need?

<img width="1551" alt="image" src="https://user-images.githubusercontent.com/11913918/122098173-c67fe080-ce10-11eb-99c6-7ff23ed9566c.png">

**Comment by conconnl** [comment]
Roland helped me by phone.
He is going to test the key we found.

**Comment by jeckodevelopment** [comment]
I think it's the Maps JavaScript API or the Maps Embed API

**Comment by roland-d** [comment]
I have implemented a global configuration option where we can set the key. Added the new key provided and the map works again.

Thank you for reporting the issue @hans2103
