### ISSUE TITLE
[jvols] Duplicate of PLT

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#27]
If you go to: https://volunteer.joomla.org/teams/production-leadership-team#members

It's an empty team: no members, no reports, no roles.

This appears to be the old URL for PLT, before moving it as Leadership Team.

Is it possible to have a redirect to the new URL for PLT?
`https://volunteer.joomla.org/leadership/production-leadership-team`

**Comment by wilsonge** [comment]
Presumably this is the difference between the current PLT and the new structure Production team (which is not the same thing as the current PLT)?

**Comment by jeckodevelopment** [comment]
No the new one should not be called PLT, I guess.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for catching that issue. In the past version the PLT, CLT and OSM were teams to, they now moved to "departments" but their entries were still in the database. Removed now.

**Comment by jeckodevelopment** [comment]
Thank you! :)
