### ISSUE TITLE
[jvols] Persistent search filters.

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#28]
If you go to https://volunteers.joomla.org/joomlers and search for `whatever` and click Enter on your keyboard, you'll see the search results. (And it's ok).

But if you click again on the `Joomlers` top menu item, the search filter is still here and you will see the search results. To see again all the joomlers you need to empty the search box and click on enter.

It could be useful to add a "Go" and a "Clear" button in order to improve the UX for the search box.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for the suggestion! Available now.

**Comment by jeckodevelopment** [comment]
Great work! :D thank you
