### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#30]
if you go to a team with roles you'll see that the members table is not responsive and sometimes the member pictures are not displayed (see certification operations team as sample), sometimes they are stretched. 
![screenshot_2016-08-30-23-31-50](https://cloud.githubusercontent.com/assets/733133/18107972/8587b2d4-6f0a-11e6-9326-bdd754cbd331.png)
![screenshot_2016-08-30-23-31-04](https://cloud.githubusercontent.com/assets/733133/18107973/85893b72-6f0a-11e6-9f4d-acf53365a0fc.png)

**Comment by sanderpotjer** [comment]
Note: homepage could use some responsive love too. So check other pages too.

**Comment by sanderpotjer** [comment]
@jeckodevelopment should be better now!

**Comment by jeckodevelopment** [comment]
It's really great.
Thank you :)
