### ISSUE TITLE
Grey bands on mobile

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#31]
If you look from mobile to the jvols homepage you'll see a grey band above and below the map. Because of the zoom the height on mobile view is too high.
Tested on Android with Google Chrome

![screenshot_2016-08-31-18-22-58](https://cloud.githubusercontent.com/assets/733133/18137310/18d0ce52-6fa8-11e6-9485-fa9a771241d9.png)

**Comment by sanderpotjer** [comment]
@jeckodevelopment the world needs to fix itself and become bigger ;-)

No, the height of the map is set, will set a different height for smaller devices. Thanks!

**Comment by jeckodevelopment** [comment]
you're welcome :P

**Comment by sanderpotjer** [comment]
Fixed

**Comment by jeckodevelopment** [comment]
Thank you!
