### ISSUE TITLE
https://volunteer.joomla.org/teams

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/volunteers.joomla.org#34]
When subteams are archived, they still remain visible in the overview of the teams.

**Comment by jeckodevelopment** [comment]
Where @mikeveeckmans ?
I can't see as "Active" archived teams.
We have a filter on top: "Active", "Archived", "All"

**Comment by sanderpotjer** [comment]
For example, https://volunteers.joomla.org/teams/think-bigger-team is archived. But showing in the overview: 
<img width="885" alt="screen shot 2016-09-01 at 18 07 18" src="https://cloud.githubusercontent.com/assets/522834/18174761/f255244a-706e-11e6-9b60-64c4e5396e45.png">

**Comment by mikeveeckmans** [comment]
indeed @sanderpotjer

**Comment by jeckodevelopment** [comment]
oh, you're right

**Comment by sanderpotjer** [comment]
Thanks for reporting, issue is fixed.
