### ISSUE TITLE
404 on old link for PLT

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#35]
The old URL for PLT was: `https://volunteers.joomla.org/working-groups/production-leadership-team`
It has a redirect to: `https://volunteers.joomla.org/teams/production-leadership-team`
This gives actually a 404 error because now PLT has been moved under Leadership
Final URL should be: `https://volunteers.joomla.org/leadership/production-leadership-team` 

Thank you

**Comment by sanderpotjer** [comment]
Redirects are active now, also for CLT & OSM. Thanks!

**Comment by jeckodevelopment** [comment]
Thank you!
