### ISSUE TITLE
Long urls break responsive view 

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#36]
If you go to `https://volunteers.joomla.org/reports` from a mobile phone you'll see that the responsive view is broken by long urls in some reports.

![screenshot_2016-09-10-10-45-32](https://cloud.githubusercontent.com/assets/733133/18409325/a1f1eccc-7744-11e6-9c14-0021e7b3ce86.png)

![screenshot_2016-09-10-10-45-29](https://cloud.githubusercontent.com/assets/733133/18409329/ad79d438-7744-11e6-803b-7616c380e0e0.png)

![screenshot_2016-09-10-10-45-24](https://cloud.githubusercontent.com/assets/733133/18409330/b69c62c4-7744-11e6-978b-728b5cee379d.png)

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks, fixed now.

**Comment by jeckodevelopment** [comment]
Thank you Sander!
