### ISSUE TITLE
Pagination display on mobile

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#37]
The pagination needs some improvements on mobile view in order to have enough space between page numbers.

![screenshot_2016-09-11-21-55-38](https://cloud.githubusercontent.com/assets/733133/18420084/c0ef64ac-786a-11e6-88d3-721f2cd6704a.png)

**Comment by sanderpotjer** [comment]
This is something for the J! template in general. See https://developer.joomla.org/news.html as well for example:

<img width="458" alt="screen shot 2016-09-11 at 22 07 58" src="https://cloud.githubusercontent.com/assets/522834/18420171/4ba49e40-786c-11e6-818a-547820227fe7.png">

**Comment by mbabker** [comment]
I swear at one point I changed this to only display the arrows on mobile and hide the numbers.

**Comment by brianteeman** [comment]
Well the good thing about github is you can check ;)

**Comment by sanderpotjer** [comment]
@mbabker thanks for the template update, is OK now:

<img width="368" alt="screen shot 2016-09-11 at 23 18 00" src="https://cloud.githubusercontent.com/assets/522834/18420587/18c219f8-7876-11e6-9d8a-70dd12c9ca2b.png">

**Comment by jeckodevelopment** [comment]
Thank you ALL :)
