### ISSUE TITLE
[RFC] About Team Contributors

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#38]
> **Contributor** The Contributor is a contributing, but not a member of a team.

Why don't we have a new list for team contributors?
It can be added between `Roles` and `Reports`.

We would have the following tabs:
- Members
- Honor Roll
- Roles
- Contributors
- Reports
- Get involved
- Contacts

Since Contributors are not regular members and they haven't the right to vote, they shouldn't be listed as members in Volunteers, but since they contribute and help the team to reach its goal, it woud be fair to include them in a dedicated list.

**Comment by wilsonge** [comment]
I disagree. They should be listed in Volunteers. They are still volunteers. But they have a different role

**Comment by jeckodevelopment** [comment]
List currently says "Members", since also the bylaws underline the difference, i suggested to have a list for them.

**Comment by wilsonge** [comment]
Then we should just change it to Volunteers. The aim was to use the "role" column to differentiate.

**Comment by jeckodevelopment** [comment]
I'm ok with this.

**Comment by wilsonge** [comment]
Closing as we have a PR :)

**Comment by sanderpotjer** [comment]
Or should the tab be "Joomlers"? Already the column name too.

**Comment by wilsonge** [comment]
I don't feel strongly over the exact name. I just feel strongly that all the people (team lead, members and contributors) should be in the same list. "Joomlers" works just as well

**Comment by sanderpotjer** [comment]
I fully agree on that too, better then having separate tabs for each of the types.
