### ISSUE TITLE
Sorted Member Lists

### ISSUE THREAD

**Issue by mbabker** [joomla/volunteers.joomla.org#39]
The member lists seem kind of random.  Can we sort them in some kind of order?

**Comment by jeckodevelopment** [comment]
+1

**Comment by sanderpotjer** [comment]
Sure! What ordering :)

By:
- name
- date started
- leader, assistant leader, members, contributors
- or... ?

**Comment by wilsonge** [comment]
I'd put leader at the top then the rest alpha (I'm making it hard I'm sure :P)

**Comment by mbabker** [comment]
I'm good with just alpha order without the extra complexity requested by some on this thread.

**Comment by sanderpotjer** [comment]
Thanks for your input guys! Members list is now sorted.
