### ISSUE TITLE
Joomler Links Broken

### ISSUE THREAD

**Issue by mbabker** [joomla/volunteers.joomla.org#4]
Old: https://volunteers.joomla.org/joomlers/michael-babker
New: https://volunteers.joomla.org/joomlers/83-michael-babker

A redirect would be good here...

**Comment by jeckodevelopment** [comment]
All the old Joomler links are broken... i guess they added the ID before of the name in order to handle "duplicated names".

**Comment by sanderpotjer** [comment]
@mbabker thnx, and yes @jeckodevelopment thats indeed the reason. Working on a redirect.

**Comment by sanderpotjer** [comment]
Old URL's redirect now, thanks for reporting @mbabker

**Comment by jeckodevelopment** [comment]
thank you @sanderpotjer
