### ISSUE TITLE
Duplicate domain name

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#40]
As reported in https://github.com/joomla/joomla-websites/issues/577

Volunteers Portal uses two different domain names:
- `volunteer.joomla.org`
- `volunteers.joomla.org`

Why?
I guess we should have only one domain: `volunteers.joomla.org` and we should redirect the "singular form" to the main one.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for the heads up about the issue in the other repo 👍 

volunteer.joomla.org is now redirecting to volunteers.joomla.org

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer
