### ISSUE TITLE
Long urls break responsive view on FAQs

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#42]
If you go to https://volunteers.joomla.org/faq

![screenshot_2016-09-15-21-35-51](https://cloud.githubusercontent.com/assets/733133/18564620/a1a1b76a-7b8c-11e6-8c31-9e445270df1d.png)
![screenshot_2016-09-15-21-35-48](https://cloud.githubusercontent.com/assets/733133/18564619/a1a13c86-7b8c-11e6-8b4c-4fbed199238d.png)

**Comment by sanderpotjer** [comment]
@mbabker this is a default Joomla article page, what about adding something like 

```
.item-page {
word-wrap: break-word;
}
```

To the main Joomla.org template?

**Comment by mbabker** [comment]
Sounds fine to me

**Comment by sanderpotjer** [comment]
Check, follow up for this issue via j.org template, PR: https://github.com/joomla/jdotorgtemplate/pull/89
