### ISSUE TITLE
Empty RSS feed

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#43]
If you go to https://volunteers.joomla.org/reports
and then click on the RSS Feed button at the end of the page, you'll see an empty RSS feed.

`https://volunteers.joomla.org/reports?filter_category=&format=feed&type=rss`

I'm sure that it depends from the top category filter...
If category is not set, it should display reports from all the categories.

**Comment by jeckodevelopment** [comment]
Even if you set the category, the button still links to: https://volunteers.joomla.org/reports?filter_category=&format=feed&type=rss 
No category ID passed.

**Comment by sanderpotjer** [comment]
@jeckodevelopment i can't duplicate the empty RSS feed issue, I do see entries.

The RSS button on the bottom is now using the filtered category as well.

**Comment by jeckodevelopment** [comment]
![jvolsrss](https://cloud.githubusercontent.com/assets/733133/18647750/cbf47d8a-7eb7-11e6-88a8-374932895456.gif)

**Comment by wilsonge** [comment]
It works fine for me doing the same thing :/ I'm using chrome though. is the browser making a difference?

**Comment by sanderpotjer** [comment]
I think I found the issue for some RSS readers. Looks like limiting the description fixes it. Testing it right now.

**Comment by sanderpotjer** [comment]
@jeckodevelopment is the feed now working for you?

**Comment by jeckodevelopment** [comment]
It works. Thanks
