### ISSUE TITLE
Automatically set "end date" for members when group is archived

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/volunteers.joomla.org#44]
Make sure all members automatically move to the honour list once a group is archived.

**Comment by zero-24** [comment]
hmm where is the code you archive groups i can just find "deplartments" & "teams" but no code that archiv them? do i miss something?

**Comment by sanderpotjer** [comment]
@zero-24 as soon as an "end date" is set, the team will be marked as "archived"

**Comment by sanderpotjer** [comment]
This has been implemented
