### ISSUE TITLE
Joomlers grid issues on mobile

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#48]
If you go to https://volunteers.joomla.org/joomlers by mobile,  you can see that joomlers are not well aligned. 
![screenshot_2016-09-22-08-10-13](https://cloud.githubusercontent.com/assets/733133/18738489/8cb3f74a-809c-11e6-8b3e-d3a7a3978fd5.png)

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for reporting, fixed now

**Comment by jeckodevelopment** [comment]
Thank you 😊
