### ISSUE TITLE
[jvols] Create new team

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#50]
@sanderpotjer can you please create a new team: "Certification Team"
It should have as subteams:
- Certification Operations Team
- Certification Marketing Team
- Certification Platform Team
- Certification Exam Team

Team should go under Open Source Matters leadership now (then under Program Department).

Thank you.

**Comment by sanderpotjer** [comment]
@jeckodevelopment team has been created: https://volunteers.joomla.org/teams/certification-team

**Comment by jeckodevelopment** [comment]
Thank you

**Comment by jeckodevelopment** [comment]
@sanderpotjer it should include all the actual subteam members, right?

**Comment by jeckodevelopment** [comment]
@sanderpotjer can you set me as TL, please?
