### ISSUE TITLE
[jvols] 404 on adding teams

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#51]
Just for information, under: https://volunteers.joomla.org/leadership/production-leadership-team#teams 
I clicked on the button `Add a Team` and i received a 404 `Team not found`

Destination URL: `https://volunteers.joomla.org/leadership?task=team.add&department=41`

I don't need to add teams under PLT at the moment, but, eventually, it doesn't work now.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for catching that bug! Fixed now.

**Comment by jeckodevelopment** [comment]
Thank you for fixing! 👍
