### ISSUE TITLE
Listed in both Active and Honour Roll

### ISSUE THREAD

**Issue by brianteeman** [joomla/volunteers.joomla.org#53]
https://volunteers.joomla.org/teams/cms-maintenance-team

You will see that Tobias is in both active and honour roll. In one sense it makes sense as it is technically accurate but in another it seems wrong.

Perhaps the honour roll entry should indicate that he is "active" again

**Comment by zero-24** [comment]
The last one is correct 👍

**Comment by zero-24** [comment]
I think it is clear as we always have the `date started` and `date ended` infos.
