### ISSUE TITLE
Notification if the user gets added to a new team

### ISSUE THREAD

**Issue by zero-24** [joomla/volunteers.joomla.org#54]
It just happen to me a few times that i was added to a team that i'm not longer part of or don't know that there is a team.

Is there any chance to get a mail (or any other info) if someone add/remove/.. the groups the user is in? specifically since you cant set your self away anymore (Ref https://github.com/joomla/joomla-websites/issues/472)

**Comment by sanderpotjer** [comment]
@zero-24 at the moment not, but I do think it is a great idea. So thanks for the suggestion!

**Comment by zero-24** [comment]
> It just happen to me a few times that i was added to a team that i'm not longer part of or don't know that there is a team.

hmm after thinking about i think this is not the regular case and we should not float our uses with mails :smile: -> Closing
