### ISSUE TITLE
Test site - A guide in home page

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/volunteers.joomla.org#55]
Hi, 

I have just checked the test site. The first impression is great, visiting a site to show our volunteering efforts.

The second impression is total confussion. I mean most users are used to the current organization. When you navigate this site, it has totally different departments, teams and roles, 

I think that the site has to clearly show in the home page a **guide** about the new organization and provide answers to the most common questions and use cases:
- Which team do I belong now? After reading the guide, it must be clear to find the department / team where a Joomlers belong.
- I want to apply as Joomler, what department / team is the right area to apply according my skills?

These use cases are the most common, If we ease this change adoption, the rest of the questions will be answered itself with the regular site usage.

The current "Become a Joomla! contibutor / How Can I Help? / Why Should I Help? / Latest Department & Team Reports" were Ok.... At this time, we have to show this guide for the current Joomlers that will reach the new **volunteers 2.0 site**. So, introductory information about the change must replace the current information to ease the movement.

**Comment by Joomv** [comment]
Hi Anibal, remember this is a playground, not the actual real thing.  The real thing will be populated with all the teams in place.  The change will be there's no CLT or PLT - but this will be split into departments. I know that Mike V is writing up a "manual" at the moment.

**Comment by sanderpotjer** [comment]
@anibalsanchez thanks for you suggestions! An on-boarding process for the Volunteers Portal is certainly something that will be improved in the next months. Helping people to find areas to contribute based on their available time and/or skills. I do also agree we need to check all pages from a "newbie" perspective that are not familiar with the common Joomla terms yet.

**Comment by anibalsanchez** [comment]
Glad to hear that introductory information will be added. In this process, it will be the key to have a smooth change.

**Comment by roland-d** [comment]
I am closing this as I believe the volunteer portal is quite common now and the new organization structure is up and running.
