### ISSUE TITLE
[jvols] Subteams Leaders are not able to change their subteams

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#56]
If you have a team, like Certification Team, which have subteams (we have 4 subteams), TL of subteams are not able to add/remove/edit membership of people involved in the subteam.
Only TL and ATL of the Parent Team are able to change subteam members and positions.

Subteam leader should be able to change team data (description, email, and so on) and to manage memberships of his/her subteam.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for reporting. Should be fixed now!

**Comment by jeckodevelopment** [comment]
Thank you!
