### ISSUE TITLE
[jvols] Mismatching info between users and archived team

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#57]
If i visit the profile of Sigrid Gramlinger, she's listed as member of  `JUG Directory Working Group`, like she's currently involved in this team. But, that team isn't active anymore, since it's archived.
Furthermore, if i go to the team page, i can see only Ruth Cheesley in the Honour Roll.

What did happen here? 
### Links

https://volunteers.joomla.org/joomlers/678-sigrid-gramlinger 
https://volunteers.joomla.org/teams/jug-directory-working-group
### Screenshots

![sigrid1](https://cloud.githubusercontent.com/assets/733133/19481784/672e1e52-954f-11e6-933f-d6cef84bfbae.PNG)

![jugdwg](https://cloud.githubusercontent.com/assets/733133/19481778/6315dca6-954f-11e6-8bbc-6bf73a8a2ea9.PNG)

**Comment by sanderpotjer** [comment]
@jeckodevelopment the "end date" is not set for here role in the archived team. #44 should fix this issue if teams are bing archived without setting an end date for the team members first. 

Corrected this for Sigrid now.

**Comment by jeckodevelopment** [comment]
Thank you
