### ISSUE TITLE
Creating report on same name /alias 

### ISSUE THREAD

**Issue by sam-suresh** [joomla/volunteers.joomla.org#58]
Creating report on same name/alias makes the report disappear. 
When it is saved, it says "Successfully saved" but its not published.

**Comment by sanderpotjer** [comment]
@sam-suresh you mean the same alias of the report title right? I do see this entry: https://volunteers.joomla.org/teams/certification-platform-team/reports/351-joomla-certification-platform-team-meeting-notes-1

**Comment by sam-suresh** [comment]
Yes. this one i just created as the original one went missing. Then I tested again with same name and it went missing again even though it says successfully saved.

**Comment by sanderpotjer** [comment]
Ok, thanks for reporting the issue!

**Comment by sanderpotjer** [comment]
@sam-suresh the issue is fixed. Thanks again for reporting!
