### ISSUE TITLE
Missing permissions after updates.

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#6]
I'm not able anymore to manage my team (Certification Operations Team) even if I'm TL.
And, as member of PLT, I was able to add members and manage team. Now I can't anymore.
Furthermore I can't add reports to Certification Operations Team.

Please check :)

**Comment by sanderpotjer** [comment]
@jeckodevelopment the permission settings are corrected, could you please test if this is working now correctly for you? Thanks!

**Comment by jeckodevelopment** [comment]
@sanderpotjer thank you. 
Still no permissions on PLT

**Comment by sanderpotjer** [comment]
@jeckodevelopment think I found the issue, your position was set as "team member" instead of "leadership team member". Could you confirm you have the permissions now?

**Comment by jeckodevelopment** [comment]
Yes it works, thank you.
But if I try to edit my PLT membership (clicking on Edit) I receive a 403 error and if i go back I see:

![usercheckin](https://cloud.githubusercontent.com/assets/733133/17849846/efdabbc4-685a-11e6-906c-963ce66e1bd6.PNG)

**Comment by sanderpotjer** [comment]
Sorry, checked your permissions but didn't closed it.

**Comment by jeckodevelopment** [comment]
Thank you very much Sander :)
