### ISSUE TITLE
Countries on the team members page

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/volunteers.joomla.org#62]

**Comment by justinherrin** [comment]
Is this something that you were thinking of? If yes, I'd agree with the change and I can take a stab at doing a PR for this...

![screen shot 2017-02-27 at 10 14 17 pm](https://cloud.githubusercontent.com/assets/13225615/23390171/711807ae-fd3a-11e6-87eb-29175f2fae4e.png)

**Comment by sanderpotjer** [comment]
@justinherrin sorry, missed your comment about the PR that was edited later... This has been implemented now.
