### ISSUE TITLE
404 Joomler not found

### ISSUE THREAD

**Issue by HALVAM** [joomla/volunteers.joomla.org#63]
Greetings. I'm having a issue with the site. It seems that something went wrong during my registration and now everytime i try to edit My Profile I get this error message.

![captura de pantalla 38](https://cloud.githubusercontent.com/assets/23493800/20336826/d0dfac4a-ab92-11e6-88e5-19327804b19b.png)

But when visiting the homepage I notice that I'm logged in (also it seems that my account isn't complete).

![image](https://cloud.githubusercontent.com/assets/23493800/20336886/2b674718-ab93-11e6-9c09-efb2c96763f6.png)

I remember that during my registration I had an sql error related to the date, after that, I tried to return to the previous page but thats when the issue started.

**Comment by sanderpotjer** [comment]
@HALVAM thank you for reporting the issue, not sure what happened there as I can't (yet) replicate the issue. But the error should be gone and you can edit your profile now. Is that correct?

**Comment by HALVAM** [comment]
Yes, I can edit my profile now, thanks. As for the error, i think it was caused because I wrote the date like DAY/MONTH/YEAR instead of MONTH/DAY. Somehow it skipped validation.

**Comment by dwrianto** [comment]
Hi @sanderpotjer and team, how've you been? Well, here I have similar issue with this one. Not a big issue tho.

I've made an account (in fact, twice) on the site, but unfortunately, all of them are now gone in Bermuda Triangle. Here's the case.

### Background
- I've created my first account on the site years ago, can't remember the date anymore (ages factor _lols_).
- The second was on 5 October 2016 and was created when MATT asked about my profile availability on the site. And also, at this point MATT told me that there was an update/upgrade performed on the site so my old data probably gone or flushed or any other possibilities. Therefore, I need to create a new one and it done.
- Both of them are successfully created and already have full bio.
- Both of them are registered under the same email.
- On 5 October and so, I can link the second created account from Glip to the page.

Here's the link that used to work http://joom.la/fOM

**Screenshot from Glip**

![img-glip_dwirianto_link](https://cloud.githubusercontent.com/assets/875973/20550565/8e0281cc-b169-11e6-9fe6-78523618e4b2.png)

### Issue
And as you can see and find it now--pls don't tell me you haven't click the link yet--the link goes to someone else's page (well, hi Joel Mbugua!).

### Questions
- Same here, big How?
- Should I make/register for a new account? _Or,_
- Can you track my issue using the registered email address, I assume dwiriantop[at]gmail[dot]com is probably still recorded in the sql?

Thank you so much for your time!

DRP

**Comment by sanderpotjer** [comment]
@dwiriantop thanks for reporting the issue. On October 5 a major downtime occurred at Joomla's hosting, causing the host to put back database backups that were 2 days old (as the more recent ones were corrupted). It looks like you have registered exactly within the time of the data loss... So I am sorry, but I can't retrieve your latest account back. Once the backup was restored Joel signed up and got the ID you initially had on the site, so thats why the joom.la link is going to a different profile.

However, I have traced back your initial account: https://volunteers.joomla.org/joomlers/1344-dwi This is now enabled and you should be able to login again. Please let me know if not.

**Comment by dwrianto** [comment]
@sanderpotjer Fantastic! Yes, I can see the profile now. But, I cannot login with my email and password. Let me try with the forgot password, no?

**Comment by sanderpotjer** [comment]
@dwiriantop yes, please use the forgot password. Let me know if that doesn't work for you.

**Comment by dwrianto** [comment]
@sanderpotjer Failed, twice, as you may see it on the log. Maybe wrong username, but I can't remember any other username. Perhaps, I need Yoda help now. May the force be with me.

**Comment by sanderpotjer** [comment]
@dwiriantop please check your email :)

**Comment by dwrianto** [comment]
@sanderpotjer Aah, it's an email! I thought it was a username field. That's why.

Thanks 👍 it works now. But, I think we don't have any field to be able to change the password thru user profile page now. Or, did I miss something here? Well, I still can use the forgot password anyways.

And, one more thing, you know, UX :) Please, please, please, change the label form Username to Email if it tends to an email.

Thank you so much Yoda! ;)

**Comment by sanderpotjer** [comment]
@dwiriantop thanks for the feedback! Looks indeed that the password fields are gone from the profiles. We will fix that!
