### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#68]
Following #65 we have a missing word here:

https://volunteers.joomla.org/faq

> Q: I want to add a team, but he/she is not in the list of Joomlers

should be:
> Q: I want to add a **person to** a team, but he/she is not in the list of Joomlers

Furthermore #66 seems to be solved.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks!
