### ISSUE TITLE
Can't edit my profile

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#7]
If I click on "Edit my Joomler Profile" nothing happens...

**Comment by mbabker** [comment]
This worked earlier.  Maybe something to do with the redirect fix?

**Comment by jeckodevelopment** [comment]
Don't know...
I've also permission issues #6

**Comment by mbabker** [comment]
Wouldn't you know it, I do too! 😂

**Comment by jeckodevelopment** [comment]
Permissions or profile?

**Comment by mbabker** [comment]
Both.  Too many permissions and the profile thing (the link is right but
it's not hitting the edit task).

**Comment by jeckodevelopment** [comment]
same here, but too less permissions

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks for reporting, should be fixed now.

**Comment by jeckodevelopment** [comment]
yes, thank you
