### ISSUE TITLE
Rights to edit user group team!

### ISSUE THREAD

**Issue by webdjam** [joomla/volunteers.joomla.org#71]
Hello @sanderpotjer,
Can you please change the right on my profile on the volunteers portal to edit the User group team, as Team lead I need the rights to edit.
Thank you,
Djamel

**Comment by jeckodevelopment** [comment]
Even if he's linked as Team Leader of User Groups Team, Djamel is not able to perform any change to the team in JVP.

**Comment by webdjam** [comment]
I have rights to edit the team profile on VJO.

**Comment by sanderpotjer** [comment]
@webdjam so it is working correctly now?

**Comment by webdjam** [comment]
Hello @sanderpotjer yes is working correctly now, thank you.
