### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/volunteers.joomla.org#72]
Asked for a password reset.
Got mail.
Verification code does not work.
Tried this two times.

**Comment by MartijnMaandag** [comment]
I still can't reset my password, but I know now how to get back in. The problem is that I saved a username and password. 
If you look at the picture one ID is called username the other emailadres.
I can get in by emailadress. As far as I can see there is no username anymore.
![volunteers](https://cloud.githubusercontent.com/assets/4639364/21685215/ff9e28ea-d360-11e6-9c20-b0bb668ef72f.png)

**Comment by zero-24** [comment]
IIRC Username is just renamed to Email? Can you try your email there?

**Comment by MartijnMaandag** [comment]
Yes when I enter my emailadress it works, so please rename "Username *" into "Emailadress *"

**Comment by sanderpotjer** [comment]
Field is now changed via language override
