### ISSUE TITLE
No profile page

### ISSUE THREAD

**Issue by JansenInternetservice** [joomla/volunteers.joomla.org#73]
I filled in all fields to make an account on https://volunteers.joomla.org but at the end I can login but there is no profile page (error 404). Something went wrong with fill in the form I think.

**Comment by sanderpotjer** [comment]
@JansenInternetservice thank you for reporting the issue. Not sure what happened yet, but your profiel wasn't created automatically. I have now manually linked a profile to your account. You might need to re-fill a couple of the profile fields, sorry for that.

**Comment by JansenInternetservice** [comment]
Sorry,

I can’t change my profile. When I change something and save, nothing happens.

**Comment by sanderpotjer** [comment]
I can't replicate the issue at the moment. Could you please logout and login and see if that works?

**Comment by JansenInternetservice** [comment]
I used Google Chrome, now I tried with Edge and that works.
Thanks, case closed.
