### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by ronoliverclarin** [joomla/volunteers.joomla.org#76]
Hi,
 
Since, I am going to be a resource speaker for Joomla Web Development again this coming January 21, 2017. I am trying to log in to the following:
https://community.joomla.org/
https://volunteers.joomla.org/ (https://volunteers.joomla.org/joomlers/1530-ron-oliver-clarin)
Sad o say, I cannot log in using the same details:
username: ronoliverclarin
e-mail address: ronoliverclarin@gmail.com
I tried to forget username and password but it is not working. The error say invalid email address.
Hope you can help me

**Comment by sanderpotjer** [comment]
@ronoliverclarin could you please login with your email as username, and check if that works?

**Comment by ronoliverclarin** [comment]
@sanderpotjer it works. Thank you. I'm excited to share Joomla again to IT/CS students.

**Comment by zero-24** [comment]
@ronoliverclarin you can close the issue than :smile:
