### ISSUE TITLE
Report titles not responsive. 

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#79]
Page /reports
Filter by Leadership > Open source matters 
And some names go out of the page box

![screenshot_20170122-195439](https://cloud.githubusercontent.com/assets/733133/22185437/471a7226-e0dd-11e6-811b-79b0b4568943.png)

**Comment by sanderpotjer** [comment]
This is fixed now

**Comment by jeckodevelopment** [comment]
Thank you
