### ISSUE TITLE
Issue in viewing the joomla.org website

### ISSUE THREAD

**Issue by dushaniw** [joomla/volunteers.joomla.org#80]
The page is not displayed properly or the site must has been crashed. I am using a standard internet connection and some pages on joomla.org loads fine (ex docs.joomla.org) But pages like https://volunteers.joomla.org/ is not loaded properly. The error I get at the bottom of the page is 
"We have detected that you are using an ad blocker. The Joomla! Project relies on revenue from these advertisements so please consider disabling the ad blocker for this domain."

But I havent use any of the ad blockers for my browser. I even tried for different browsers but it is still the same
![Uploading Screenshot from 2017-01-31 00-27-57.png…]()

**Comment by mbabker** [comment]
There is a known issue affecting the CDN used by the websites, see https://github.com/joomla/joomla-websites/issues/835

Many of the websites were temporarily updated to load the resources from the local site versus the CDN until the issue is resolved.

**Comment by sanderpotjer** [comment]
CDN loading disabled for now

@dushaniw website should display correctly again after refreshing the page

**Comment by dushaniw** [comment]
yes it displays fine now. Thank you @mbabker  and @sanderpotjer :)
