### ISSUE TITLE
FAQ needs update on Structure

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#82]
In FAQ is old Structure like "Leadership Team":
![1](https://cloud.githubusercontent.com/assets/8235763/23012001/453423da-f424-11e6-9d31-c4349fa6df76.JPG)

**Comment by sanderpotjer** [comment]
@franz-wohlkoenig thanks! FAQ is updated now with new department terms

**Comment by ghost** [comment]
Thanks @sanderpotjer
