### ISSUE TITLE
Get to know Joomlers link goes nowhere

### ISSUE THREAD

**Issue by Sandra97** [joomla/volunteers.joomla.org#83]
This button on the homepage links to the homepage. Isn't it a bit strange?
![2](https://cloud.githubusercontent.com/assets/4682328/23326593/7d4de208-fad5-11e6-86ef-0d7a5ad85c05.png)

**Comment by jeckodevelopment** [comment]
Should go to /joomlers ? 😃

**Comment by sanderpotjer** [comment]
@Sandra97 link is fixed, thanks for reporting!
