### ISSUE TITLE
[RFC] Contact Form on the My Profile Page

### ISSUE THREAD

**Issue by justinherrin** [joomla/volunteers.joomla.org#85]
Hello all. I think it is odd that there is a contact form on the "My Profile" page that lets me contact myself. It's fun I guess, but is it really needed or does it just add "clutter" to the page?

Thoughts?

**Comment by nileshprasad137** [comment]
I agree , even I was confused when I used it for first time.

**Comment by sanderpotjer** [comment]
@justinherrin that is indeed odd! Has been changed now.
