### ISSUE TITLE
[vol] Saving report with the same name. 

### ISSUE THREAD

**Issue by sam-suresh** [joomla/volunteers.joomla.org#86]
Saving report with the same name cause the report to vanish. 

For example is a report titled "Joomla! Certification Team Report" already exist and creating same title and saving caused the report to vanish. 

Expected result: Saving should throw error without vanishing the report.

**Comment by jeckodevelopment** [comment]
IIRC this problem was already reported and fixed in the past.

**Comment by sam-suresh** [comment]
Yes it happened to me too in the past and reported in joomla-websites repo. 
As the time of reporting this, it happened again and caused report to lost.

**Comment by sanderpotjer** [comment]
@sam-suresh thanks for reporting. This should be fixed now.
