### ISSUE TITLE
[question] How to represent the Board of Directors?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#87]
In the new version of JVP, we have the Departments as Leadership structure.
How are we going to represent the new Board of Directors?

Thanks

**Comment by zero-24** [comment]
What about the OSM Group?

**Comment by jeckodevelopment** [comment]
That's what i thought, even if it's not a real "Department".

**Comment by zero-24** [comment]
Is the OSM a department?

**Comment by jeckodevelopment** [comment]
According to this structure it's not a department:

![](https://community.joomla.org/images/blogs/leadership-blog/joomla_leadership_structure-800.png)

It's something more "inclusive", because all Dept. Coordinators are member of the Board of Directors and Officers.

**Comment by zero-24** [comment]
So it is a group of members?

**Comment by zero-24** [comment]
Group with members ;)

**Comment by mbabker** [comment]
You've got two quirks with making the volunteer portal show correctly for these conditions.

1. It's not really set up for individual roles like President or Secretary.  You kind of get around this with the department leads by having the department entity and assigning the lead to that entity (which is in essence a special type of team).
2. The board is basically just a team, but it's not a team as it would be defined in the portal.  So you kind of need one more special team thing just for representing the entirety of the board within one entity.

**Comment by zero-24** [comment]
What about a normal team that is linked from the navigation? And contain everyone involved as member?

**Comment by jeckodevelopment** [comment]
I guess that Departments should be intended as "SuperTeams", not just one man team, but they should include all the people part of the Departmental Coordination Team of which the Director (Dept. Coord) is the Team Leader. I can recall that in the call for nomination, the official title was "Department Coordinator Team Leader". 

I agree with your (2). The board is just a team, Maybe it can be represented in the Department Tab with its name. 
We have the Officers (includes: President, Vice President, Secretary, Treasurer)
We have the Board of Directors and Officers (aka Full Board) that includes the Officers and the Dept. Coordinators.

Furthermore, we need to define how to display also the Ombudsman and the Advisory Board.

**Comment by zero-24** [comment]
They are all members of the OSM where you can add a role done :)

**Comment by jeckodevelopment** [comment]
Formally with the new structure, you should consider OSM as an "umbrella" that contains all the Departments and Teams. So each member of each team is automatically a class-3 member of OSM. 
Each team leader of each team (main teams, not subteams) is a class-2 member of OSM.
Each Dept. Coordinator Team Leader (aka Director) and each Officer is a class-1 member of OSM.

About the Advisory Board, i'm not sure they should be considered as full member of OSM.
And about the Ombudsman, he/she should be considered a member of OSM with a special role.

**Comment by sanderpotjer** [comment]
@jeckodevelopment Please see https://volunteers.joomla.org/board-of-directors. You should be able to add reports too for this special "department" marked as Board of Directors.

Is this what you had in mind?

**Comment by jeckodevelopment** [comment]
I guess yes. Will test tomorrow. From mobile it looks fine and seems to be what we need. I'll get back to you tomorrow. Thanks!
