### ISSUE TITLE
[compliance] Membership Roll

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#88]
According to the OSM Bylaws we have to record some personal and "technical" data of each member.
![membership-roll](https://cloud.githubusercontent.com/assets/733133/23519902/e4ba35e8-ff78-11e6-857d-ac19da4b431d.PNG)

Are we ready to do it?
Can we require a change also to existing profiles?

## Fields / Info missing 
- Date of involvement (see note 1)
- Membership class (see note 2)
- Mailing address (see note 3)
- Termination of membership (see note 1)

### Notes
1. Date of involvement. We can record the date in which they're appointed in any position when their team leader / Dept. Coord. add them to a specific team.
2. Membership Class. We should ensure that a new "record" is created when a member change his/her class of membership, e.g. appointment as Team Leader or Dept. Coordinator.
3. Mailing address. This field should be accessible just to the OSM Secretary, if needed, otherwise must be an hidden field.

**Comment by zero-24** [comment]
Why do OSM need my Mail?

**Comment by jeckodevelopment** [comment]
I can understand your thoughts Tobias, but the bylaws says clearly what is needed.

**Comment by zero-24** [comment]
Is this just to contact me? You can do this via the contact form and also see the mail anyway ;)

**Comment by jeckodevelopment** [comment]
Rules 😸

**Comment by mbabker** [comment]
Can someone who was involved with setting up the current bylaws explain the need for the mailing address?  At least we'd then know what the requirement is driving it versus what could be considered a "m'eh, we just want this info" request, I'm at least assuming it's in part driven by New York state requirements.

**Comment by zero-24** [comment]
What is the problem if you already have that info? If you are logged in you can see my mail so Rules are fullfield :)

**Comment by mbabker** [comment]
Your email address would be available, but nowhere are we collecting physical mailing addresses, one of the bylaw requirements.  The only times I've ever given the project a mailing address were when signing the JCA and OSM NDA agreements.

**Comment by zero-24** [comment]
How did you register with the v.j.org ?

**Comment by mbabker** [comment]
You're asking me to remember something from 3 years ago, not happening 😆

**Comment by jeckodevelopment** [comment]
Well, i registered on JVP ages ago.
But, each former leadership team member (i did for PLT) wrote his/her physical mail address in a spreadsheet on Google Drive.

**Comment by zero-24** [comment]
The thing i mean is that we have a mail in v.j.org any the secretary can access that mail if needed so we are done with that rule? Even it maybe makes no sense?

**Comment by mbabker** [comment]
There is not mailing address field in the volunteer portal.  The rules state that both a physical mailing address and electronic mailing address (email) have to be on file for each individual, it's not an either/or thing.  So yes, your email address is in the system, but no, the listing is not compliant with the bylaws at this time.

**Comment by jeckodevelopment** [comment]
> the listing is not compliant with the bylaws at this time.

That's why i opened this "issue" :)

**Comment by sanderpotjer** [comment]
So to sum things up: a physical mailing address fields is needed in the profiles which should be accessible by the secretary only. But only for those that are "member" of a team, right? Should we enforce people to fill this in if they are a member before using the Volunteer Portal?

**Comment by jeckodevelopment** [comment]
1. Yes, the field should be visible only to secretary.
2. Members (all levels), not for contributors.
3. Yes, we need to enforce the rule also for existing members, please.

**Comment by jeckodevelopment** [comment]
@sanderpotjer can I have an update on this, please?

**Comment by sanderpotjer** [comment]
## Requested "Fields / Info missing"
### Date of involvement
This is already stored for each volunteer for all teams involved, as start date and end date in the `#__volunteers_members` table, and visible on the site

### Membership class
This is already stored for each volunteer for all teams involved. But the position was editable for existing members. This is now changed, so you can no longer change a position from "member" to "team leader" for example. In this way it is forced to create a new entry for the new position with the correct start date, and set the end date for the previous position to "archive". In this way we also keep the records correct of the involvement over the time in a team.

<img width="932" alt="screen shot 2017-04-15 at 16 27 06" src="https://cloud.githubusercontent.com/assets/522834/25064364/0a06f1d6-21f9-11e7-93fd-37f091530346.png">
changed into:
<img width="929" alt="screen shot 2017-04-15 at 16 32 07" src="https://cloud.githubusercontent.com/assets/522834/25064367/19ef7370-21f9-11e7-83f0-a2e23c4ae426.png">


### Mailing address
This has been changed now:
1) Upon login the portal checks if a user is an active member of a team
2) If this is the case and mailing address is not complete the user is redirect to the profile edit page to fill in the fields, and can't click on any other page. This will be the notice:
<img width="934" alt="screen shot 2017-04-15 at 16 13 00" src="https://cloud.githubusercontent.com/assets/522834/25064240/b3cc6ac8-21f6-11e7-9505-9a651f900481.png">

<img width="999" alt="screen shot 2017-04-15 at 16 13 15" src="https://cloud.githubusercontent.com/assets/522834/25064251/e6c31c06-21f6-11e7-8b6f-434fc46c89a3.png">

3) The address, city, zip/postal code and country fields are required fields, only for active members
4) The secretary can access the mailing fields via the backend

### Termination of membership 
This is already stored for each volunteer for all teams involved, as start date and end date in the `#__volunteers_members` table, and visible on the site

@jeckodevelopment could you please check if this covers all required changes? If so, we can release an update to get this process activated.

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer 
I guess that all these changes make JVP compliant.
Please deploy ;)

**Comment by sanderpotjer** [comment]
@jeckodevelopment this is now deployed!

**Comment by jeckodevelopment** [comment]
Thanks
