### ISSUE TITLE
[jvols] Introtext for "GSoC"-Team wrong Typeface

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#89]
![bildschirmfoto 2017-03-15 um 19 47 11](https://cloud.githubusercontent.com/assets/8235763/23965491/68bdec4c-09b8-11e7-9a17-3f4c1918f9a2.JPG)

**Comment by jeckodevelopment** [comment]
It's because it's not plain text box

**Comment by sanderpotjer** [comment]
@franz-wohlkoenig thanks! Probably copy-pasted with markup. Cleaned now.

**Comment by ghost** [comment]
thanks @sanderpotjer and @jeckodevelopment
