### ISSUE TITLE
Blank contact tab if the user is not logged in

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#9]
If you go (as guest, not logged) to volunteers.joomla.org and click on "Get in touch" you'll see the button "Please use the Contact form to contact this team":

![buttontab](https://cloud.githubusercontent.com/assets/733133/17832059/bc63de9e-66fa-11e6-9a01-7e7004a7a304.PNG)

If you click on that button, sometimes it works and it shows the Notice as follows (the url becomes `#contact`):

![infotab](https://cloud.githubusercontent.com/assets/733133/17832080/d9d7d034-66fa-11e6-9a57-93c56b11a9bd.PNG)

Sometimes it doesn't work properly and you'll see a blank tab, like that:
![blanktab](https://cloud.githubusercontent.com/assets/733133/17832086/ff2f648c-66fa-11e6-98e9-00410e662333.PNG)

In this case, the url will remain: `#getinvolved`
and if you try to open each of the others tab you'll continue see the blank tab (like the one above) and the url will be always `#getinvolved`.

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks, behaviour was indeed different when access directly to a team-url or browsing via the teams overview. Should be fixed now.

**Comment by jeckodevelopment** [comment]
Great! Thank you! :)
