### ISSUE TITLE
[Question] About permissions

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#90]
Should the Secretary be able to see the backend or have the proper permission to "change" the involvement of a member (of all classes) according to the real status or the decision of the full board?

Thanks.

![secretary1](https://cloud.githubusercontent.com/assets/733133/23966031/3a08dcd4-09ba-11e7-8101-bc61dfdcdbc1.PNG)

**Comment by sanderpotjer** [comment]
@jeckodevelopment you should be able to manage everything on the site now

**Comment by jeckodevelopment** [comment]
It looks like i've the permissions. 
Thanks!
