### ISSUE TITLE
[jvols] Teams > Contact: "To:"- and "From:"-Fields looks ugly

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#91]
![bildschirmfoto 2017-03-15 um 20 01 58](https://cloud.githubusercontent.com/assets/8235763/23966183/bee7ca50-09ba-11e7-8345-f52827c31ede.JPG)

**Comment by sanderpotjer** [comment]
@franz-wohlkoenig what browser are you using?

**Comment by ghost** [comment]
macOS Sierra, 10.12.3: Firefox 52.0 (64-bit)

**Comment by sanderpotjer** [comment]
@franz-wohlkoenig thanks, should be fine now!

**Comment by ghost** [comment]
@sanderpotjer Thanks, is fine now.
