### ISSUE TITLE
Unit test is listed under the wrong Dept.

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#92]
![wrongdept](https://cloud.githubusercontent.com/assets/733133/23966327/41eb66e6-09bb-11e7-874a-bd66e1b7f4a5.PNG)

The correct Department is "Production Department".

https://volunteers.joomla.org/teams/unit-testing-working-group

**Comment by sanderpotjer** [comment]
@jeckodevelopment thanks! The subteams were not update to the new department of the main team, now they are.

**Comment by jeckodevelopment** [comment]
Thank you @sanderpotjer
