### ISSUE TITLE
Blank page (almost) while editing OSM reports

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#95]
I tried to edit the Board meeting report i just published and i can't do it.
I see a sort of blank page in which i can't edit nothing

![1](https://cloud.githubusercontent.com/assets/733133/24197867/b0421c5a-0f03-11e7-86ff-e93b100c6f17.PNG)

**Comment by sanderpotjer** [comment]
@jeckodevelopment this is fixed now

**Comment by jeckodevelopment** [comment]
Thanks
