### ISSUE TITLE
Department Inheriting Team Members

### ISSUE THREAD

**Issue by mbabker** [joomla/volunteers.joomla.org#96]
https://volunteers.joomla.org/departments/production

The accessibility team members are showing up incorrectly.

**Comment by jeckodevelopment** [comment]
@joomv is this something related to db modifications?

**Comment by sanderpotjer** [comment]
@mbabker I only see you listed?

**Comment by Sandra97** [comment]
It's ok now. I presume you can close this issue

**Comment by Sandra97** [comment]
Thank you!

**Comment by mbabker** [comment]
Definitely good now.  Yesterday it was showing Accessibility Team members on the department page.
