### ISSUE TITLE
Bord of Directors needs Update

### ISSUE THREAD

**Issue by ghost** [joomla/volunteers.joomla.org#97]
In "[Meet the new Open Source Matters (OSM) Board of Directors](https://community.joomla.org/blogs/leadership/3108-meet-the-new-open-source-matters-board-of-directors.html)" are changes, but not shown in "[Board of Directors](https://volunteers.joomla.org/board-of-directors)":
![bildschirmfoto 2017-03-25 um 06 57 00](https://cloud.githubusercontent.com/assets/8235763/24319853/adbdf360-1128-11e7-9f49-743811f0c7a3.JPG)

**Comment by jeckodevelopment** [comment]
On it now :)
Leave me the time to be at my PC after the election :P

**Comment by ghost** [comment]
@jeckodevelopment no Pressure, only concern to forget;-)

**Comment by jeckodevelopment** [comment]
See #98
