### ISSUE TITLE
Board of Directors doesn't reflect automatically changes to Departments

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/volunteers.joomla.org#98]
After the election I changed the Department Coordinators for 2 Depts (Programs, Legal) and are not reflected automatically to the Board, even if former Directors are automatically moved to Honour roll.

**Comment by ghost** [comment]
thats what i want to write now;-)

**Comment by jeckodevelopment** [comment]
So you don't have to

**Comment by mbabker** [comment]
@jeckodevelopment Make them "Departmental Coordinator" instead of "Departmental Coordination Team Leader"

**Comment by jeckodevelopment** [comment]
Done.
Thanks
