### ISSUE TITLE
[jvols] Joomla! World Conference Team	(JWC) URL to https

### ISSUE THREAD

**Issue by zero-24** [joomla/volunteers.joomla.org#99]
https://volunteers.joomla.org/teams/world-conference-team

### Actual

Website http://conference.joomla.org

### Expected

Website https://conference.joomla.org

**Comment by sanderpotjer** [comment]
@zero-24 teams can change those urls themselves, but corrected this one

**Comment by zero-24** [comment]
Thanks.
